(()=>{'use strict';
const root=document.querySelector('#app'),params=new URLSearchParams(location.search);let config={theme:params.get('theme')==='IN'?'IN':'SF',auth:params.get('auth')||'loggedIn',values:{},current:{},install:true},slide=0,expanded=false,query='',favorite=false;
const esc=s=>String(s??'').replace(/[&<>"']/g,x=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[x]));
const art=(i,cls='',alt='')=>`<img class="${cls}" src="assets/${config.theme.toLowerCase()}/${i}.webp" alt="${esc(alt)}" draggable="false">`;
const button=(name,icon='')=>`<button data-go="${esc(name)}">${icon}<span>${esc(name)}</span></button>`;
const navKeys={Home:'首页',Activity:'活动',Wallet:'钱包',Agent:'推广',Account:'账户','我的':'账户','个人中心':'账户','APP下载':'下载APP','客服':'客服','取款':'提款','提现':'提款','登录':'登入注册','注册':'登入注册','VIP 页入口':'VIP','个人中心':'账户'};
function go(name){name=navKeys[name]||name;if(config.auth==='loggedOut'&&['钱包','充值','提款','账户'].includes(name))name='登入注册';if(name==='首页'){window.scrollTo({top:0,behavior:'smooth'});return;}if(parent!==window&&['登入注册','活动','推广','VIP','账户','钱包','充值','提款','设置','客服','站内信','用户验证'].includes(name)){parent.postMessage({type:'ngss3-preview-navigation',page:name},location.protocol==='file:'?'*':location.origin);return;}const dialog=document.querySelector('dialog');dialog.querySelector('h2').textContent=name;dialog.showModal();}
function render(){const sf=config.theme==='SF',signed=config.auth==='loggedIn',v=config.values||{},nav=(config.nav||(sf?['首页','活动','VIP','钱包','我的']:['推广','活动','首页','钱包','我的'])).map(n=>n==='APP下载'&&config.appReplacement&&config.current?.bottomNav?.appReplacementEnabled?.[config.auth]?(config.current.bottomNav.appReplacement?.[config.auth]||n):n);document.body.dataset.theme=config.theme;
const cards=sf?[[9,'Mahjong Ways 2'],[16,'Golden Empire'],[15,'Fortune Gems'],[10,'Fortune Gems 2'],[13,'Hip Hop Panda'],[14,'Wild Ape'],[12,'Win Win Won'],[11,'Candy Burst'],[17,'Pinata Wins']]:[[13,"Gladiator’s Glory"],[14,'Caishen Wins'],[15,'Guardians of Ice & Fire'],[16,'Win Win Fish Prawn Crab'],[17,'Mask Carnival'],[18,'Galactic Gems']];
const active=cards.filter(([,n],i)=>n.toLowerCase().includes(query.toLowerCase())&&(!favorite||i%3===0)&&(!sf||['热门','全部',undefined].includes(config.category)||(config.category==='JILI'?[1,2,3].includes(i):config.category==='PG'?![1,2,3].includes(i):false)));
const activity=sf?[[8,'神秘彩金'],[18,'大转盘'],[19,'神秘矿场'],[20,'会员日'],[7,'连赢活动']]:[[42,'推广活动'],[43,'存款活动'],[43,'投注金额活动']];
const navArt=sf?{'首页':22,'活动':23,'VIP':24,'钱包':25,'我的':26,'账户':26}:{'推广':45,'活动':46,'首页':44,'钱包':47,'我的':48,'账户':48};
root.innerHTML=`<div class="theme-page"><header>${sf?art(6,'logo','NGSS'):'<button class="menu" data-go="游戏">▦</button><strong class="logo-text">NGSS</strong>'}<div class="header-actions">${signed?button('钱包','<b class="balance">'+(sf?'🟡 970.8 ＋':'◉')+'</b>')+button('客服','♧')+button('账户','●'):button('登录')+button('注册')}<button data-go="语言" aria-label="语言">◎</button></div></header>
${!sf?`<div class="money"><button class="money-balance" data-go="钱包">${art(3)}<b>${signed?'0.00':'登录查看'}</b><span>＋</span></button>${button(signed?'充值':'登录')}${button(signed?'提现':'注册')}</div>`:''}
<section class="hero" aria-label="首页轮播"><div class="hero-art" ${sf?`style="background-image:url('assets/sf/${[4,3,2][slide]}.webp')"`:''}></div>${sf?`<div class="hero-copy"><h1>${['邀请好友','最高奖励','每日惊喜'][slide]}</h1><strong>${['$666','$88888','$888'][slide]}</strong></div>`:`${art(11,'hero-person')}<div class="ranking"><b>排行榜</b>${[50,52,54,56].map((i,n)=>button('排行榜',art(i)+`<small>${n+1}</small>`)).join('')}</div><div class="hero-tools">${[9,8,7,5].map((i,n)=>button(['转盘','礼物','奖励','惊喜'][n],art(i))).join('')}</div>`}<div class="slides">${[0,1,2].map(n=>`<button data-slide="${n}" aria-label="轮播 ${n+1}" aria-pressed="${n===slide}"></button>`).join('')}</div></section>
<section class="activity" data-component="activity">${activity.map(([i,n])=>button(n,art(i))).join('')}</section>
${sf?`<div class="categories">${['热门','JILI','JDB','PG','PP','全部'].map(n=>`<button data-category="${n}" aria-pressed="${(config.category||'热门')===n}">${n==='热门'?'♨ ':''}${n}</button>`).join('')}</div>`:''}
<div class="search-panel" ${config.searchOpen?'':'hidden'}><label>搜索游戏<input type="search" value="${esc(query)}" placeholder="Game name"></label></div><section class="games" data-component="games">${Array.from({length:sf?20:12},(_,i)=>active.length?active[i%active.length]:null).filter(Boolean).map(([i,n])=>`<button class="game" data-go="${esc(n)}">${art(i,'',n)}</button>`).join('')}${!active.length?'<p>没有符合的游戏</p>':''}</section>
${sf?'<button class="more" data-more>更多 ›</button>':`<section class="rewards">${art(21,'elephant')}${art(20,'ornament')}<h2>每次存款均可获得奖励<small>最高可达 <b>100%</b></small></h2><div class="reward-grid">${[25,27,28,29].map((i,n)=>`<button data-go="充值" class="reward reward-${n}"><strong>${['100% 奖金','375 奖金','500 奖金','500 奖金'][n]}</strong><span>${['首次充值','二次充值','三次充值','四次充值'][n]}</span>${art(i)}</button>`).join('')}</div></section><footer><div class="footer-links">${[31,32,33,34].map((i,n)=>button(['活动中心','帮助中心','关于我们','联系我们'][n],art(i))).join('')}</div><p>加入社区</p><div class="socials">${[36,37,38,39,40,41].map((i,n)=>button(['Telegram','Facebook','WhatsApp','Instagram','YouTube','TikTok'][n],art(i))).join('')}</div></footer><div class="bottom-filters"><button data-search>筛选</button><button data-favorite aria-pressed="${favorite}">收藏</button><button data-all>全部游戏</button></div>`}
${sf?`<div class="quick-tools" data-component="shortcuts"><button data-search aria-label="搜索游戏">⌕</button>${config.install?button('下载APP','⇩'):''}<button data-top>↑<small>TOP</small></button></div><div class="activity-float ${expanded?'expanded':''}" data-component="shortcuts"><button data-expand aria-label="${expanded?'收起活动':'展开活动'}" aria-expanded="${expanded}">${expanded?'⌄':'⌃'}</button>${(expanded?[[29,'连赢奖金'],[33,'幸运转盘'],[32,'限时奖励'],[28,'会员日'],[27,'彩金解锁'],[30,'神秘彩金']]:[[33,'幸运转盘']]).map(([i,n])=>button(n,art(i))).join('')}</div>`:''}
<nav class="bottom-nav" aria-label="底部导航">${nav.map((n,i)=>`<button data-go="${esc(n)}" class="${i===2?'center':''}" aria-current="${(navKeys[n]||n)==='首页'?'page':'false'}">${navArt[n]!=null?art(navArt[n]):'<i>◇</i>'}<span>${esc(n)}</span></button>`).join('')}</nav><dialog><button class="close" aria-label="关闭">×</button><h2></h2><p>此页面用于外观与操作预览。</p><button class="close">返回</button></dialog></div>`;
root.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>go(b.dataset.go));root.querySelectorAll('.close').forEach(b=>b.onclick=()=>root.querySelector('dialog').close());root.querySelectorAll('[data-slide]').forEach(b=>b.onclick=()=>{slide=Number(b.dataset.slide);render()});root.querySelector('[data-expand]')?.addEventListener('click',()=>{expanded=!expanded;render()});root.querySelectorAll('[data-search]').forEach(b=>b.onclick=()=>{config.searchOpen=!config.searchOpen;render();root.querySelector('input')?.focus({preventScroll:true})});root.querySelector('input')?.addEventListener('input',e=>{query=e.target.value;const at=e.target.selectionStart;render();const input=root.querySelector('input');input.focus({preventScroll:true});try{input.setSelectionRange(at,at)}catch{}});root.querySelector('[data-favorite]')?.addEventListener('click',()=>{favorite=!favorite;render()});root.querySelector('[data-all]')?.addEventListener('click',()=>{favorite=false;query='';render()});root.querySelector('[data-top]')?.addEventListener('click',()=>go('首页'));root.querySelector('[data-more]')?.addEventListener('click',()=>go('游戏'));root.querySelectorAll('[data-category]').forEach(b=>b.onclick=()=>{config.category=b.dataset.category;query='';render()});
if(v.shortcuts==='关闭'||v.shortcuts===null)root.querySelectorAll('[data-component="shortcuts"]').forEach(n=>n.hidden=true);
if(v.footerStyle==='关闭'||v.footerStyle===null)root.querySelector('footer')?.setAttribute('hidden','');
const home=config.current?.gameLayout?.home;if(home?.quick===false)root.querySelector('.money')?.setAttribute('hidden','');if(home?.promotions===false)root.querySelector('.activity')?.setAttribute('hidden','');
if(config.install&&!sf){const download=document.createElement('button');download.className='install-entry';download.textContent='⇩ App';download.setAttribute('aria-label','下载App');download.onclick=()=>go('下载APP');root.querySelector('.theme-page').append(download);}
const alt=v.alternateSpec;if(alt?.placement&&!v.alternateDisabled&&alt.target&&(!alt.authScope||alt.authScope==='both'||alt.authScope===config.auth)){const b=document.createElement('button');b.className='alternate-entry';b.textContent=alt.target;b.onclick=()=>go(alt.target);root.querySelector('.theme-page').append(b);}

}
window.addEventListener('message',e=>{if(e.source!==parent||parent===window||(location.protocol!=='file:'&&e.origin!==location.origin)||e.data?.type!=='ngss3-preview-config')return;const c=e.data.config;if(!['IN','SF'].includes(c?.theme))return;config=c;render()});render();if(parent!==window)parent.postMessage({type:'ngss3-preview-ready'},location.protocol==='file:'?'*':location.origin);
})();
