'use strict';
const R=Reward,C=Copy,$=id=>document.getElementById(id);let cfg=R.load(),lang='zh-CN';
function previews(){const t=cfg.texts[lang];$('previewName').textContent=t.name;$('previewIntro').textContent=t.intro;$('previewRules').textContent=C.rules(cfg,lang);const errors=R.validate(cfg);$('errors').textContent=errors.join('\n');$('save').disabled=errors.length>0;$('risk').textContent=cfg.cap===''?'当前不设单用户赠送上限。':'当前本活动单人上限：'+cfg.cap+' INR；不包含其他活动奖励。';$('wagerField').hidden=cfg.wallet!=='cash';$('wagerField').style.display=cfg.wallet==='cash'?'flex':'none';$('wagerHint').hidden=cfg.wallet!=='cash';}
function draw(){['wallet','multiple','cap','budget'].forEach(k=>$(k).value=cfg[k]);$('ageEnabled').checked=cfg.ageEnabled;$('name').value=cfg.texts[lang].name;$('intro').value=cfg.texts[lang].intro;
 $('ages').innerHTML=cfg.ages.map((a,i)=>`<div class="field"><input aria-label="时长${i+1}" data-age="${i}" type="number" min="0" value="${a.value}"><select aria-label="时长单位${i+1}" data-unit="${i}"><option value="d" ${a.unit==='d'?'selected':''}>天</option><option value="m" ${a.unit==='m'?'selected':''}>月</option></select><button data-del-age="${i}">删除</button></div>`).join('');
 $('bands').innerHTML=cfg.bands.map((b,i)=>`<div class="field"><span>金额下限 ${i+1}</span><input aria-label="金额下限${i+1}" data-band="${i}" value="${C.esc(b)}"><button data-del-band="${i}">删除</button></div>`).join('');matrix();previews();}
function matrix(){$('matrix').innerHTML=`<table><thead><tr><th>注册时长</th>${cfg.bands.map((b,i)=>`<th>${C.esc(b)} ${cfg.bands[i+1]?'至不足 '+C.esc(cfg.bands[i+1]):'及以上'} INR</th>`).join('')}</tr></thead><tbody>${cfg.ages.map((a,i)=>!cfg.ageEnabled&&i?'':`<tr><th>${cfg.ageEnabled?C.age(a,'zh-CN')+(cfg.ages[i+1]?' 至不足 '+C.age(cfg.ages[i+1],'zh-CN'):' 及以上'):'不限制'}</th>${cfg.cells[i].map((v,j)=>`<td><select aria-label="奖励类型 ${i+1}-${j+1}" data-type="${i},${j}"><option value="percent" ${v.type==='percent'?'selected':''}>百分比</option><option value="fixed" ${v.type==='fixed'?'selected':''}>固定金额</option></select> <input aria-label="奖励值 ${i+1}-${j+1}" data-value="${i},${j}" value="${C.esc(v.value)}"> <span>${v.type==='percent'?'%':'INR'}</span></td>`).join('')}</tr>`).join('')}</tbody></table>`;}
$('locale').onchange=e=>{lang=e.target.value;draw();};['name','intro'].forEach(k=>$(k).oninput=e=>{cfg.texts[lang][k]=e.target.value;previews();});['wallet','multiple','cap','budget'].forEach(k=>$(k).oninput=e=>{cfg[k]=e.target.value;previews();});$('ageEnabled').onchange=e=>{cfg.ageEnabled=e.target.checked;matrix();previews();};
document.addEventListener('change',e=>{const d=e.target.dataset;if(d.age!==undefined)cfg.ages[+d.age].value=Number(e.target.value);if(d.unit!==undefined)cfg.ages[+d.unit].unit=e.target.value;if(d.band!==undefined)cfg.bands[+d.band]=e.target.value;if(d.type!==undefined||d.value!==undefined){const [i,j]=(d.type??d.value).split(',').map(Number);cfg.cells[i][j][d.type!==undefined?'type':'value']=e.target.value;}if(Object.keys(d).length){matrix();previews();}});
document.addEventListener('click',e=>{const d=e.target.dataset;if(d.delAge!==undefined&&cfg.ages.length>1){const i=+d.delAge;cfg.ages.splice(i,1);cfg.cells.splice(i,1);draw();}if(d.delBand!==undefined&&cfg.bands.length>1){const i=+d.delBand;cfg.bands.splice(i,1);cfg.cells.forEach(r=>r.splice(i,1));draw();}});
$('addAge').onclick=()=>{if(cfg.ages.length>=8)return;const a=cfg.ages.at(-1);cfg.ages.push({value:a.value+(a.unit==='d'?7:1),unit:a.unit});cfg.cells.push(cfg.bands.map(()=>({type:'percent',value:'1'})));draw();};$('addBand').onclick=()=>{if(cfg.bands.length>=8)return;try{cfg.bands.push(R.money(R.minor(cfg.bands.at(-1))+100000));cfg.cells.forEach(r=>r.push({type:'percent',value:'1'}));draw();}catch(e){$('errors').textContent=e.message;}};
$('save').onclick=()=>{if(R.validate(cfg).length)return;cfg.revision++;try{localStorage.setItem(R.KEY,JSON.stringify(cfg));$('saved').textContent='已保存。充值页和活动详情将使用相同规则。';}catch(e){$('saved').textContent='浏览器无法保存，请导出配置。';}};
$('restorePreset').onclick=()=>{for(const k of ['ages','bands','cells','wallet','multiple','cap','budget','ageEnabled'])cfg[k]=R.clone(R.defaults[k]);draw();$('saved').textContent='已带入推荐奖励，请保存。';};draw();
