'use strict';
window.ChannelBasic=(function(){
 const el=id=>document.getElementById(id),local=d=>new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16);
 let draft,lang='zh-CN';const ids=['startAt','endAt','ipLimit','deviceLimit','validFirst','validDeposit','validTurnover','validCount','marketing','layout','background','icon','activityIntro'];
 const modes=['nameMode','introMode','rulesMode','memberMode','validMode','showText'];
 function defaults(){const s=new Date();s.setHours(0,0,0,0);const e=new Date(s);e.setFullYear(e.getFullYear()+1);return {startAt:local(s),endAt:local(e),ipLimit:0,deviceLimit:0,memberMode:'all',memberLevels:[],validMode:'any',validFirst:0,validDeposit:0,validTurnover:0,validCount:0,terminals:['h5','android','ios','pwa'],nameMode:'system',introMode:'system',rulesMode:'system',rulesText:{},introText:{},marketing:false,layout:'自定义',background:'绿色',icon:'奖品',showText:'show',activityIntro:''};}
 function system(){const n=RewardHub.defaults.items.find(x=>x.id===draft.id).name;const value=draft.rewardMode==='percent'?draft.rate+'%':draft.demoReward+' INR';const req=draft.type==='recommended'?(lang==='en'?'Deposit exactly ':lang==='zh-TW'?'充值金額等於':'充值金额等于')+draft.threshold+' INR':(lang==='en'?'Deposit from ':lang==='zh-TW'?'充值金額自':'充值金额自')+draft.threshold+' INR'+(draft.maxAmount?(lang==='en'?' to under ':lang==='zh-TW'?'至未滿':'至不足')+draft.maxAmount+' INR':'');const intro=lang==='en'?'Receive a reward when your deposit qualifies.':lang==='zh-TW'?'充值符合條件，即可獲得額外獎勵。':'充值符合条件，即可获得额外奖励。';const rules=lang==='en'?`${req}. Reward: ${value}. Daily limit: ${draft.dailyCap} INR, ${draft.dailyCount} claim(s). Rewards are verified after successful payment.`:lang==='zh-TW'?`${req}，可得${value}。每日最高${draft.dailyCap} INR，限${draft.dailyCount}次。支付成功後核驗，符合條件可與其他優惠分別計算。`:`${req}，可得${value}。每日最高${draft.dailyCap} INR，限${draft.dailyCount}次。支付成功后核验，符合条件可与其他优惠分别计算。`;const cash=draft.wallet==='现金钱包';const wallet=lang==='en'?(cash?'Cash wallet':'Bonus wallet'):lang==='zh-TW'?(cash?'現金錢包':'彩金錢包'):draft.wallet;const payout=lang==='en'?(' Reward wallet: '+wallet+'. '+(cash?'Required turnover: reward × '+draft.wager+'.':'Bonus wallet terms apply.')):lang==='zh-TW'?(' 派獎錢包：'+wallet+'。'+(cash?'打碼要求：獎勵金額 × '+draft.wager+'倍。':'彩金使用條件依錢包規則。')):(' 派奖钱包：'+wallet+'。'+(cash?'打码要求：奖励金额 × '+draft.wager+'倍。':'彩金使用条件依钱包规则。'));return {name:n[lang],intro,rules:rules+payout};}
 function refresh(){if(!draft)return;const b=draft.basic,auto=system();el('wagerField').hidden=draft.wallet!=='现金钱包';el('wagerHint').hidden=draft.wallet!=='现金钱包';el('editName').readOnly=b.nameMode==='system';el('editName').value=b.nameMode==='system'?auto.name:draft.name[lang];el('intro').readOnly=b.introMode==='system';el('intro').value=b.introMode==='system'?auto.intro:b.introText[lang]||'';el('customRules').hidden=b.rulesMode!=='custom';el('previewRules').hidden=b.rulesMode==='custom';el('customRules').value=b.rulesText[lang]||'';el('previewRules').textContent=auto.rules;el('memberLevels').hidden=b.memberMode!=='specified';el('previewName').textContent=el('editName').value;el('previewIntro').textContent=el('intro').value;el('previewName').hidden=el('previewIntro').hidden=b.showText==='hide';el('previewIcon').textContent='🎁';document.querySelector('.banner-preview').style.background=({'绿色':'#14554b','红色':'#632d37','黄色':'#695220','紫色':'#49376d','暗银':'#383d4a','橘色':'#714129','蓝色':'#234c70'})[b.background];}
 function mount(item){draft=Reward.clone(item);draft.basic={...defaults(),...draft.basic};draft.basic.rulesText={...draft.basic.rulesText};draft.basic.introText={...draft.basic.introText};ids.forEach(id=>{const e=el(id);e[e.type==='checkbox'?'checked':'value']=draft.basic[id];});modes.forEach(name=>document.querySelectorAll(`input[name="${name}"]`).forEach(e=>e.checked=e.value===draft.basic[name]));document.querySelectorAll('.terminal').forEach(e=>e.checked=draft.basic.terminals.includes(e.value));[...el('memberLevels').options].forEach(e=>e.selected=draft.basic.memberLevels.includes(e.value));refresh();}
 ids.forEach(id=>el(id).addEventListener('input',e=>{draft.basic[id]=e.target.type==='checkbox'?e.target.checked:e.target.value;refresh();}));
 modes.forEach(name=>document.querySelectorAll(`input[name="${name}"]`).forEach(e=>e.addEventListener('change',()=>{draft.basic[name]=e.value;refresh();})));
 el('basicLocale').onchange=e=>{lang=e.target.value;refresh();};el('editName').oninput=e=>{draft.name[lang]=e.target.value;el('previewName').textContent=e.target.value;};el('intro').oninput=e=>{draft.basic.introText[lang]=e.target.value;el('previewIntro').textContent=e.target.value;};el('customRules').oninput=e=>draft.basic.rulesText[lang]=e.target.value;
 el('memberLevels').onchange=e=>draft.basic.memberLevels=[...e.target.selectedOptions].map(x=>x.value);document.querySelectorAll('.terminal').forEach(e=>e.onchange=()=>draft.basic.terminals=[...document.querySelectorAll('.terminal:checked')].map(x=>x.value));
 function read(){const b=draft.basic;if(!b.startAt||!b.endAt||b.endAt<=b.startAt)throw Error('请填写有效的活动期间。');if(!b.terminals.length)throw Error('请选择活动申领终端。');if(b.memberMode==='specified'&&!b.memberLevels.length)throw Error('请选择参与会员层级。');for(const key of ['ipLimit','deviceLimit','validFirst','validDeposit','validTurnover','validCount'])if(!Number.isFinite(Number(b[key]))||Number(b[key])<0)throw Error('会员限制须为非负数。');for(const l of ['zh-CN','zh-TW','en']){if(b.nameMode==='custom'&&!draft.name[l]?.trim())throw Error('请填写各语系活动名称。');if(b.introMode==='custom'&&!b.introText[l]?.trim())throw Error('请填写各语系宣传简介。');if(b.rulesMode==='custom'&&!b.rulesText[l]?.trim())throw Error('请填写各语系规则说明。');}return {basic:Reward.clone(b),name:b.nameMode==='system'?Reward.clone(RewardHub.defaults.items.find(x=>x.id===draft.id).name):Reward.clone(draft.name)};}
 function update(values){if(draft){Object.assign(draft,values);refresh();}}
 return {mount,read,update};
})();
