'use strict';
window.ChannelBasic=(function(){
 const el=id=>document.getElementById(id),local=d=>new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16);
 let draft;const lang='zh-CN';const ids=['periodMode','startAt','endAt','ipLimit','deviceLimit','layout','background','icon','activityIntro'];
 const modes=['nameMode','introMode','rulesMode','showText'];
 function defaults(){const s=new Date();s.setHours(0,0,0,0);const e=new Date(s);e.setFullYear(e.getFullYear()+1);return {periodMode:'scheduled',startAt:local(s),endAt:local(e),ipLimit:0,deviceLimit:0,terminals:['h5','android','ios','pwa'],nameMode:'system',introMode:'system',rulesMode:'system',rulesText:{},introText:{},layout:'自定义',background:'绿色',icon:'奖品',showText:'show',activityIntro:''};}
 function system(locale=lang){const lang=locale;
  const en=lang==='en',tw=lang==='zh-TW',n=RewardHub.defaults.items.find(x=>x.id===draft.id)?.name||window.DepositCatalogue?.make(draft.type).name||draft.name;
  if(draft.promotionView)return {name:'推荐好友开宝箱',intro:'最高奖励0\n推荐好友\n过期自动派发。',rules:'1，发展好友开宝箱，完成不同人数，可获取对应的宝箱金额，发展越多奖励越高\n2，此活动属平台活动赠送，同时享有其他代理奖励和佣金，即可享受多种平台奖励，互不冲突，推广人数以活动期间内新注册的直属下级计算；\n3，奖励仅限在iOS_APP,Android_APP,PC,H5端领取，根据领取和派发规则派发奖励；\n4，本活动所赠送的奖金需根据配置(打码量倍数)有效投注才能提现，投注不限游戏平台；\n5，本活动仅限帐号本人进行正常的人为操作，禁止租借，使用外挂，机器人，不同帐号对赌，互刷，套利，协议，利用漏洞，群控或其他技术手段参与，否则将取消或扣除奖励，冻结，甚至拉入黑名单；\n6，为避免文字理解差异，平台将保留本活动最终解释权。'};
  if(draft.type==='first'){const c=DepositCatalogue.firstConfig(draft);c.basic={...c.basic,rulesMode:'system'};return {name:n[lang],intro:c.texts[lang].intro||Reward.defaults.texts[lang].intro,rules:Copy.rules(c,lang)};}
  const reward=v=>v.type==='percent'?v.value+'%':v.value+' INR';
  const req=draft.conditions?.mode==='cumulative'&&!draft.ranges?.length?(en?'Reward: ':tw?'贈送：':'赠送：')+(draft.rewardMode==='percent'?draft.rate+'%':draft.demoReward+' INR'):draft.ranges?.length?draft.ranges.map(r=>r.min+(r.max?'–'+r.max:en?' or more':tw?'以上':'以上')+' INR → '+reward(r)).join('；'):(draft.type==='recommended'?(en?'Deposit exactly ':tw?'充值金額等於':'充值金额等于'):draft.type==='cumulative'?(en?'Daily deposit total at least ':tw?'每日累計充值滿':'每日累计充值满'):(en?'Deposit at least ':tw?'單筆充值滿':'单笔充值满'))+draft.threshold+' INR → '+(draft.rewardMode==='percent'?draft.rate+'%':draft.demoReward+' INR');
  const count=draft.claimLimit||draft.dailyCount||'1',period=draft.countPeriod==='total'?(en?'in total':tw?'累計':'累计'):(en?'per day':tw?'每日':'每日');
  const intro=en?'Receive a reward when your deposit qualifies.':tw?'充值符合條件，即可獲得額外獎勵。':'充值符合条件，即可获得额外奖励。';
  const limits=en?`${period}: ${count} claim(s). ${draft.dailyCap?'Daily reward cap: '+draft.dailyCap+' INR.':''}`:`${period}限${count}次。${draft.dailyCap?(tw?'每日贈送上限':'每日赠送上限')+draft.dailyCap+' INR。':''}`;
  const split=draft.wallet==='现金和彩金钱包',cash=draft.wallet==='现金钱包';const wallet=split?(en?`Cash ${draft.cashShare}% / bonus ${100-Number(draft.cashShare)}%`:tw?`現金${draft.cashShare}%／彩金${100-Number(draft.cashShare)}%`:`现金${draft.cashShare}%／彩金${100-Number(draft.cashShare)}%`):en?(cash?'Cash wallet':'Bonus wallet'):tw?(cash?'現金錢包':'彩金錢包'):draft.wallet;
  const turnover=(draft.type==='recommended'||draft.conditions?.mode==='exact')&&draft.recommendedTurnover!==undefined?(en?'Required turnover: ':tw?'提款所需打碼量：':'提款所需打码量：')+draft.recommendedTurnover+' INR.':(en?'Required turnover: reward amount × ':tw?'打碼要求：獎勵金額 × ':'打码要求：奖励金额 × ')+draft.wager+(en?'.':'倍。');
  const windowNames={day:['一日','一日','one day'],rolling7:['最近7日（滚动）','最近7日（滾動）','the rolling last 7 days'],activity:['活动开始后','活動開始後','since the activity started'],lifetime:['历史累积','歷史累積','all deposit history']};const c=draft.conditions;const q=c&&['cumulative','both'].includes(c.mode)?(en?'Total eligible deposits in ':tw?'符合活動方式與通道的充值，於':'符合活动方式与通道的充值，于')+windowNames[c.window][en?2:tw?1:0]+(en?' must reach ':tw?'累計達':'累计达')+c.minimum+' INR。':'';
  const basis=draft.conditions&&(draft.rewardMode==='percent'||draft.ranges?.some(r=>r.type==='percent'))?(en?' Percentage rewards use this successful deposit amount. ':tw?' 比例獎勵按本筆成功充值金額計算。':' 比例奖励按本笔成功充值金额计算。'):'';const rules=q+req+basis+(draft.ranges?.length?(en?'. Amount ranges include both ends. ':'。充值区间含上下限。'):(en?'. ':'。'))+limits+(draft.cap?(en?' Activity reward cap per member: '+draft.cap+' INR.':(tw?'每人活動獎勵上限':'每人活动奖励上限')+draft.cap+' INR。'):'')+(en?' Reward wallet: ':tw?' 派獎錢包：':' 派奖钱包：')+wallet+(en?'. ':'。')+turnover+(en?' Verified after successful payment.':tw?'支付成功後核驗，符合條件的活動分別計算。':'支付成功后核验，符合条件的活动分别计算。');
  return {name:n[lang],intro,rules:tw?rules.replace('充值区间含上下限','充值區間含上下限'):rules};
 }
 function refresh(){if(!draft)return;const b=draft.basic,auto=system();el('activityDates').hidden=b.periodMode==='always';const absolute=!draft.promotionView&&(draft.conditions?.mode==='exact'||!draft.conditions&&draft.type==='recommended');el('wagerField').hidden=draft.wallet==='彩金钱包'||absolute;el('wagerHint').hidden=el('wagerField').hidden;el('turnoverRow').hidden=!absolute;el('editName').readOnly=b.nameMode==='system';el('editName').value=b.nameMode==='system'?auto.name:draft.name[lang];el('intro').hidden=b.introMode!=='custom';el('intro').value=b.introMode==='system'?auto.intro:b.introText[lang]||'';el('customRules').hidden=b.rulesMode!=='custom';el('previewRules').hidden=b.rulesMode==='custom';el('customRules').value=b.rulesText[lang]||'';el('previewRules').textContent=auto.rules;el('previewName').textContent=el('editName').value;el('previewIntro').textContent=el('intro').value;el('previewName').hidden=el('previewIntro').hidden=b.showText==='hide';el('previewIcon').textContent='🎁';document.querySelector('.banner-preview').style.backgroundColor=({'绿色':'#14554b','红色':'#632d37','黄色':'#695220','紫色':'#49376d','暗银':'#383d4a','橘色':'#714129','蓝色':'#234c70'})[b.background];document.querySelector('.banner-preview').style.backgroundImage='url(activity-assets/'+(b.backgroundImage||'59b779.png')+')';if(b.iconImage&&/^[a-zA-Z0-9_-]+\.png$/.test(b.iconImage)){const img=document.createElement('img');img.alt='';img.src='activity-assets/'+b.iconImage;img.style.cssText='width:100px;height:110px;object-fit:contain';el('previewIcon').replaceChildren(img);}}
 function mount(item){draft=Reward.clone(item);draft.basic=RewardHub.cleanBasic({...defaults(),...draft.basic});draft.basic.rulesText={...draft.basic.rulesText};draft.basic.introText={...draft.basic.introText};ids.forEach(id=>{const e=el(id);e[e.type==='checkbox'?'checked':'value']=draft.basic[id];});modes.forEach(name=>document.querySelectorAll(`input[name="${name}"]`).forEach(e=>e.checked=e.value===draft.basic[name]));refresh();}
 ids.forEach(id=>el(id).addEventListener('input',e=>{draft.basic[id]=e.target.type==='checkbox'?e.target.checked:e.target.value;refresh();}));
 modes.forEach(name=>document.querySelectorAll(`input[name="${name}"]`).forEach(e=>e.addEventListener('change',()=>{draft.basic[name]=e.value;refresh();})));
 el('editName').oninput=e=>{draft.name[lang]=e.target.value;el('previewName').textContent=e.target.value;};el('intro').oninput=e=>{draft.basic.introText[lang]=e.target.value;el('previewIntro').textContent=e.target.value;};el('customRules').oninput=e=>draft.basic.rulesText[lang]=e.target.value;
 document.querySelectorAll('[data-background-image],[data-icon-image]').forEach(e=>e.onclick=()=>{if(e.dataset.backgroundImage)draft.basic.backgroundImage=e.dataset.backgroundImage;else draft.basic.iconImage=e.dataset.iconImage;refresh();});
 function read(){const b=draft.basic;if(b.periodMode!=='always'&&(!b.startAt||!b.endAt||b.endAt<=b.startAt))throw Error('请填写有效的活动期间。');for(const key of ['ipLimit','deviceLimit'])if(!Number.isFinite(Number(b[key]))||Number(b[key])<0)throw Error('会员限制须为非负数。');for(const l of (draft.type==='first'?['zh-CN','zh-TW','en','bn']:['zh-CN','zh-TW','en'])){if(l!==lang){const auto=system(l);if(b.introMode==='custom'&&!b.introText[l]?.trim())b.introText[l]=auto.intro;if(b.rulesMode==='custom'&&!b.rulesText[l]?.trim())b.rulesText[l]=auto.rules;}if(b.nameMode==='custom'&&!draft.name[l]?.trim())throw Error('请填写各语系活动名称。');if(b.introMode==='custom'&&!b.introText[l]?.trim())throw Error('请填写各语系宣传简介。');if(b.rulesMode==='custom'&&!b.rulesText[l]?.trim())throw Error('请填写各语系规则说明。');}return {basic:Reward.clone(b),name:b.nameMode==='system'?Reward.clone(RewardHub.defaults.items.find(x=>x.id===draft.id)?.name||window.DepositCatalogue?.make(draft.type).name||draft.name):Reward.clone(draft.name)};}
 function update(values){if(draft){Object.assign(draft,values);refresh();}}
 return {mount,read,update,snapshot:()=>({basic:Reward.clone(draft.basic),name:Reward.clone(draft.name)})};
})();
