(function(){
 const R=Reward;
 const words={
 'zh-CN':{wallet:{cash:'现金钱包',bonus:'彩金钱包'},day:'天',month:'个月',above:'及以上',to:'至不足',fixed:'固定',deposit:'首充金额',age:'注册时长',reward:'奖励',title:'规则说明',rule:'首次成功充值时，按注册时长和首充金额匹配下表，仅发放一档奖励，每位会员限一次。未达条件的首充不补发，后续充值不参与。',percent:'百分比奖励以首充成功金额计算，金额保留两位小数，舍去不足一分的部分。',auto:'奖励核验通过后自动派发。',stack:'符合条件时，可与每日任务及在线充值奖励叠加，各项奖励分别计算。',cap:'本活动单人奖励上限',uncap:'本活动不设单人奖励上限。',wager:'打码要求：奖励金额 ×',x:'倍。',bonus:'彩金使用与转换条件以彩金钱包规则为准。',all:'不限制',status:{eligible:'已达标，等待核验',ineligible:'首充未达活动条件',notFirst:'已完成过首充，无法再次参加',invalid:'资料暂不可用',pending:'奖励派发中',unknown:'正在确认入账结果',failed:'派发未完成，等待处理',posted:'奖励已入账',budget:'暂不接受新资格，请稍后查看',login:'登录后查看资格',waiting:'等待首次充值',paused:'活动暂停新参与',ended:'活动已结束',offline:'暂时无法取得资料'},view:'查看奖励记录',login:'登录',depositCTA:'前往充值',wait:'等待自动派发',retry:'刷新状态',period:'活动时间以活动中心公布为准。'},
 'zh-TW':{wallet:{cash:'現金錢包',bonus:'彩金錢包'},day:'天',month:'個月',above:'及以上',to:'至未滿',fixed:'固定',deposit:'首充金額',age:'註冊時長',reward:'獎勵',title:'規則說明',rule:'首次成功充值時，按註冊時長和首充金額匹配下表，僅發放一檔獎勵，每位會員限一次。未達條件的首充不補發，後續充值不參與。',percent:'百分比獎勵以首充成功金額計算，金額保留兩位小數，捨去不足一分的部分。',auto:'獎勵核驗通過後自動派發。',stack:'符合條件時，可與每日任務及線上充值獎勵疊加，各項獎勵分別計算。',cap:'本活動單人獎勵上限',uncap:'本活動不設單人獎勵上限。',wager:'打碼要求：獎勵金額 ×',x:'倍。',bonus:'彩金使用與轉換條件以彩金錢包規則為準。',all:'不限制',status:{eligible:'已達標，等待核驗',ineligible:'首充未達活動條件',notFirst:'已完成過首充，無法再次參與',invalid:'資料暫不可用',pending:'獎勵派發中',unknown:'正在確認入帳結果',failed:'派發未完成，等待處理',posted:'獎勵已入帳',budget:'暫不接受新資格，請稍後查看',login:'登入後查看資格',waiting:'等待首次充值',paused:'活動暫停新參與',ended:'活動已結束',offline:'暫時無法取得資料'},view:'查看獎勵紀錄',login:'登入',depositCTA:'前往充值',wait:'等待自動派發',retry:'重新整理狀態',period:'活動時間以活動中心公布為準。'},
 en:{wallet:{cash:'Cash wallet',bonus:'Bonus wallet'},day:'days',month:'months',above:'or more',to:'to under',fixed:'Fixed',deposit:'First deposit',age:'Membership period',reward:'Reward',title:'How it works',rule:'Your membership period and first successful deposit select one reward tier. One reward per member. A first deposit that does not qualify cannot qualify later; later deposits do not count.',percent:'Percentage rewards use the successful first deposit amount, rounded down to two decimal places.',auto:'Rewards are sent automatically after verification.',stack:'Eligible daily task and online deposit rewards may also apply. Each reward is calculated separately.',cap:'Maximum reward per member',uncap:'This activity has no per-member reward cap.',wager:'Required turnover: reward amount ×',x:'.',bonus:'Bonus use and conversion follow the bonus wallet rules.',all:'Any',status:{eligible:'Qualified, awaiting verification',ineligible:'First deposit did not qualify',notFirst:'First deposit already completed',invalid:'Details unavailable',pending:'Sending reward',unknown:'Confirming wallet result',failed:'Reward pending resolution',posted:'Reward credited',budget:'New participation is temporarily unavailable',login:'Sign in to check eligibility',waiting:'Awaiting your first deposit',paused:'New participation is paused',ended:'Activity ended',offline:'Details temporarily unavailable'},view:'View reward record',login:'Sign in',depositCTA:'Go to deposit',wait:'Await automatic reward',retry:'Refresh status',period:'See the activity center for the activity dates.'}};
 const esc=s=>String(s).replace(/[&<>"']/g,x=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[x]));
 function age(a,l){return a.value===0?({'zh-CN':'注册即享','zh-TW':'註冊即享',en:'From registration'})[l]:`${a.value} ${a.unit==='d'?words[l].day:words[l].month}`;}
 function table(c,l){const w=words[l];return `<div class="scroll"><table><thead><tr><th>${w.age}</th>${c.bands.map((b,i)=>`<th>${esc(b)} ${i+1<c.bands.length?w.to+' '+esc(c.bands[i+1]):w.above}<br>${esc(c.currency)}</th>`).join('')}</tr></thead><tbody>${c.ages.map((a,i)=>!c.ageEnabled&&i?'':`<tr><td>${c.ageEnabled?age(a,l)+' '+(c.ages[i+1]?w.to+' '+age(c.ages[i+1],l):w.above):w.all}</td>${c.cells[i].map(v=>`<td>${v.type==='percent'?esc(v.value)+'%':w.fixed+' '+esc(v.value)+' '+esc(c.currency)}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`;}
 function rules(c,l){const w=words[l];if(c.basic?.rulesMode==='custom'&&c.basic.rulesText?.[l]?.trim())return c.basic.rulesText[l];return [w.rule,w.percent,w.auto+' '+w.wallet[c.wallet]+'.',c.wallet==='cash'?w.wager+' '+c.multiple+' '+w.x:w.bonus,c.cap===''?w.uncap:w.cap+': '+c.cap+' '+c.currency,w.stack,w.period].join('\n\n');}
 window.Copy={words,esc,age,table,rules};
})();
