(function(){
 const R=Reward;
 const words={
 'zh-CN':{wallet:{cash:'现金钱包',bonus:'彩金钱包'},day:'天',month:'月',above:'及以上',to:'至不足',fixed:'固定',deposit:'充值金额',age:'注册时长',reward:'奖励',title:'规则说明',rule:'首次成功充值时，按注册时长和首充金额匹配下表，仅发放一档奖励，每位会员限一次。未达条件的首充不补发，后续充值不参与。',percent:'百分比奖励以首充成功金额计算，金额保留两位小数，舍去不足一分的部分。',auto:'奖励核验通过后自动派发。',stack:'符合条件时，可与每日任务及在线充值奖励叠加，各项奖励分别计算。',cap:'本活动单用户赠送上限',uncap:'本活动不设单用户赠送上限。',wager:'打码要求：奖励金额 ×',x:'倍。',bonus:'彩金使用与转换条件以彩金钱包规则为准。',all:'不限制',status:{eligible:'已达标，等待核验',ineligible:'首充未达活动条件',notFirst:'已完成过首充，无法再次参加',invalid:'资料暂不可用',pending:'奖励派发中',unknown:'正在确认入账结果',failed:'派发未完成，等待处理',posted:'奖励已入账',budget:'暂不接受新资格，请稍后查看',login:'登录后查看资格',waiting:'等待首次充值',paused:'活动暂停新参与',ended:'活动已结束',offline:'暂时无法取得资料'},view:'查看奖励记录',login:'登录',depositCTA:'前往充值',wait:'等待自动派发',retry:'刷新状态',period:'活动时间以活动中心公布为准。'},
 'zh-TW':{wallet:{cash:'現金錢包',bonus:'彩金錢包'},day:'天',month:'月',above:'及以上',to:'至未滿',fixed:'固定',deposit:'充值金額',age:'註冊時長',reward:'獎勵',title:'規則說明',rule:'首次成功充值時，按註冊時長和首充金額匹配下表，僅發放一檔獎勵，每位會員限一次。未達條件的首充不補發，後續充值不參與。',percent:'百分比獎勵以首充成功金額計算，金額保留兩位小數，捨去不足一分的部分。',auto:'獎勵核驗通過後自動派發。',stack:'符合條件時，可與每日任務及線上充值獎勵疊加，各項獎勵分別計算。',cap:'本活動單人獎勵上限',uncap:'本活動不設單人獎勵上限。',wager:'打碼要求：獎勵金額 ×',x:'倍。',bonus:'彩金使用與轉換條件以彩金錢包規則為準。',all:'不限制',status:{eligible:'已達標，等待核驗',ineligible:'首充未達活動條件',notFirst:'已完成過首充，無法再次參與',invalid:'資料暫不可用',pending:'獎勵派發中',unknown:'正在確認入帳結果',failed:'派發未完成，等待處理',posted:'獎勵已入帳',budget:'暫不接受新資格，請稍後查看',login:'登入後查看資格',waiting:'等待首次充值',paused:'活動暫停新參與',ended:'活動已結束',offline:'暫時無法取得資料'},view:'查看獎勵紀錄',login:'登入',depositCTA:'前往充值',wait:'等待自動派發',retry:'重新整理狀態',period:'活動時間以活動中心公布為準。'},
 bn:{wallet:{cash:'ক্যাশ ওয়ালেট',bonus:'বোনাস ওয়ালেট'},day:'দিন',month:'মাস',above:'বা বেশি',to:'থেকে কম',fixed:'নির্দিষ্ট',deposit:'ডিপোজিট',age:'নিবন্ধনের মেয়াদ',reward:'বোনাস',title:'নিয়ম',rule:'নিবন্ধনের মেয়াদ ও প্রথম সফল ডিপোজিটের পরিমাণ অনুযায়ী একটি ধাপের বোনাস পাবেন। সদস্যপ্রতি একবার। প্রথম ডিপোজিটে শর্ত পূরণ না হলে পরে এই বোনাস পাওয়া যাবে না।',percent:'শতাংশ বোনাস প্রথম সফল ডিপোজিটের পরিমাণে গণনা হবে। দশমিকের পর দুই ঘর রেখে বাকিটা বাদ যাবে।',auto:'যাচাই শেষে বোনাস স্বয়ংক্রিয়ভাবে জমা হবে।',stack:'শর্ত পূরণ হলে দৈনিক টাস্ক ও অনলাইন ডিপোজিটের বোনাসও পেতে পারেন। প্রতিটি বোনাস আলাদা করে গণনা হয়।',cap:'সদস্যপ্রতি বোনাস সীমা',uncap:'সদস্যপ্রতি আলাদা সীমা নেই। মোট অফার বাজেট প্রযোজ্য।',wager:'বাজির শর্ত: বোনাস ×',x:'গুণ।',bonus:'বোনাস ব্যবহার ও রূপান্তরে বোনাস ওয়ালেটের নিয়ম প্রযোজ্য।',all:'যেকোনো মেয়াদ',status:{eligible:'যোগ্য, যাচাই বাকি',ineligible:'শর্ত পূরণ হয়নি',notFirst:'প্রথম ডিপোজিট সম্পন্ন',invalid:'তথ্য নেই',pending:'বোনাস জমা হচ্ছে',unknown:'জমা যাচাই চলছে',failed:'প্রক্রিয়া চলছে',posted:'বোনাস জমা হয়েছে',budget:'নতুন অংশগ্রহণ বন্ধ',login:'লগইন করুন',waiting:'প্রথম ডিপোজিটের অপেক্ষায়',paused:'অংশগ্রহণ স্থগিত',ended:'অফার শেষ',offline:'তথ্য আপাতত নেই'},view:'বোনাসের রেকর্ড',login:'লগইন',depositCTA:'ডিপোজিট করুন',wait:'বোনাসের অপেক্ষা করুন',retry:'আবার দেখুন',period:'অফার কেন্দ্রে প্রকাশিত সময় প্রযোজ্য।'},
 en:{wallet:{cash:'Cash wallet',bonus:'Bonus wallet'},day:'days',month:'months',above:'or more',to:'to under',fixed:'Fixed',deposit:'First deposit',age:'Membership period',reward:'Reward',title:'How it works',rule:'Your membership period and first successful deposit select one reward tier. One reward per member. A first deposit that does not qualify cannot qualify later; later deposits do not count.',percent:'Percentage rewards use the successful first deposit amount, rounded down to two decimal places.',auto:'Rewards are sent automatically after verification.',stack:'Eligible daily task and online deposit rewards may also apply. Each reward is calculated separately.',cap:'Maximum reward per member',uncap:'This activity has no per-member reward cap.',wager:'Required turnover: reward amount ×',x:'.',bonus:'Bonus use and conversion follow the bonus wallet rules.',all:'Any',status:{eligible:'Qualified, awaiting verification',ineligible:'First deposit did not qualify',notFirst:'First deposit already completed',invalid:'Details unavailable',pending:'Sending reward',unknown:'Confirming wallet result',failed:'Reward pending resolution',posted:'Reward credited',budget:'New participation is temporarily unavailable',login:'Sign in to check eligibility',waiting:'Awaiting your first deposit',paused:'New participation is paused',ended:'Activity ended',offline:'Details temporarily unavailable'},view:'View reward record',login:'Sign in',depositCTA:'Go to deposit',wait:'Await automatic reward',retry:'Refresh status',period:'See the activity center for the activity dates.'}};
 const esc=s=>String(s).replace(/[&<>"']/g,x=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[x]));
 const rangeCopy={
  'zh-CN':{d:'日',m:'月',note:'区间含下限，不含上限；“+”表示及以上。'},
  'zh-TW':{d:'日',m:'月',note:'區間含下限，不含上限；「+」表示及以上。'},
  en:{d:'d',m:'mo',note:'Lower bound included; upper bound excluded. “+” means or more.'},
  bn:{d:'দিন',m:'মাস',note:'শুরুর সীমা অন্তর্ভুক্ত, শেষের সীমা নয়। “+” অর্থ বা বেশি।'}
 };
 function age(a,l){return a.value===0?({'zh-CN':'已注册','zh-TW':'已註冊',en:'Registered',bn:'নিবন্ধিত'})[l]:`${a.value} ${a.unit==='d'?words[l].day:words[l].month}`;}
 function ageRange(a,next,l){const u=rangeCopy[l],space=['en','bn'].includes(l)?' ':'';return !next?a.value+space+u[a.unit]+'+':a.unit===next.unit?a.value+'~'+next.value+space+u[a.unit]:a.value+space+u[a.unit]+'~'+next.value+space+u[next.unit];}
 function amountRange(b,next){return esc(b)+(next?'~'+esc(next):'+');}
 function axes(l,currency){const w=words[l];return `<th class="rule-axes" scope="col"><span class="axis-amount">${w.deposit} →<small>${esc(currency)}</small></span><span class="axis-age">${w.age} ↓</span></th>`;}
 function table(c,l){const w=words[l];return `<div class="scroll"><table class="reward-rules"><thead><tr>${axes(l,c.currency)}${c.bands.map((b,i)=>`<th scope="col">${amountRange(b,c.bands[i+1])}</th>`).join('')}</tr></thead><tbody>${c.ages.map((a,i)=>!c.ageEnabled&&i?'':`<tr><th scope="row">${c.ageEnabled?ageRange(a,c.ages[i+1],l):w.all}</th>${c.cells[i].map(v=>`<td>${v.type==='percent'?esc(v.value)+'%':w.fixed+' '+esc(v.value)+' '+esc(c.currency)}</td>`).join('')}</tr>`).join('')}</tbody></table></div><p class="mini muted range-note">${rangeCopy[l].note}</p>`;}
 function rules(c,l){const w=words[l];if(c.basic?.rulesMode==='custom'&&c.basic.rulesText?.[l]?.trim())return c.basic.rulesText[l];return [w.rule,w.percent,w.auto+' '+w.wallet[c.wallet]+'.',c.wallet==='cash'?w.wager+' '+c.multiple+' '+w.x:w.bonus,c.cap===''?w.uncap:w.cap+': '+c.cap+' '+c.currency,w.stack,w.period].join('\n\n');}
 window.Copy={words,esc,age,ageRange,amountRange,axes,table,rules};
})();
