(function(){
 'use strict';const D=DepositCatalogue,H=RewardHub,R=Reward,E=H.escape,$=id=>document.getElementById(id);let bundle=D.load(),draft=null,view=new URLSearchParams(location.search).get('tab')==='deposit'?'deposit':'all';
 const fields={threshold:'threshold',reward:'demoReward',rate:'rate',wallet:'wallet',wager:'wager',cashShare:'cashShare',activityBudget:'budget',activityCap:'cap',dailyCap:'dailyCap',claimLimit:'claimLimit',countPeriod:'countPeriod',activityMethod:'method',recommendedTurnover:'recommendedTurnover',taskPoints:'points',rewardMode:'rewardMode'};
 const descriptions={first:'按注册时长与首次充值金额匹配一次奖励。',deposit:'在线、银行、虚拟币充值按金额区间赠送。',channel:'指定在线支付通道，按充值金额赠送。',recommended:'充值金额等于推荐金额时额外赠送，可与充值赠送叠加。',cumulative:'按日累计成功充值，达到门槛时发放奖励。',single:'每笔成功充值达到门槛，按次数上限赠送。'};
 const terminals={h5:'H5领取',android:'Android APP领取',ios:'IOS APP领取',pwa:'PWA'},stamp=()=>new Date().toISOString(),format=v=>v?new Date(v).toLocaleString('sv-SE'):'—';
 function note(x,action){x.updatedAt=stamp();x.records=[...(x.records||[]),{at:x.updatedAt,action}];}
 function draw(){
  document.querySelectorAll('[data-view]').forEach(e=>e.setAttribute('aria-selected',String(e.dataset.view===view)));$('filterFamily').disabled=view==='deposit';$('rewardFilter').hidden=view!=='deposit'&&$('filterFamily').value!=='deposit';$('budgetEntry').hidden=view!=='deposit';
  const search=$('searchName').value.trim().toLowerCase(),type=$('filterType').value,state=$('filterStatus').value,from=$('createdFrom').value,to=$('createdTo').value;
  const rows=bundle.items.filter(x=>(!search||x.name['zh-CN'].toLowerCase().includes(search))&&(type==='all'||type===D.subtype(x))&&(state==='all'||D.status(x,bundle)===state)&&(!from||(x.createdAt||x.basic.startAt).slice(0,10)>=from)&&(!to||(x.createdAt||x.basic.startAt).slice(0,10)<=to)).sort((a,b)=>Number(!!b.pinned)-Number(!!a.pinned));
  $('activityRows').innerHTML=rows.map(x=>{const enabled=bundle.selected.includes(x.id);return `<tr data-activity="${E(x.id)}"><td><button data-pin="${E(x.id)}">${x.pinned?'取消置顶':'置顶'}</button></td><td>${E(x.name['zh-CN'])}<small class="activity-subtitle">${E(D.subtypes[D.subtype(x)])}</small></td><td>充值活动</td><td>${x.type==='recommended'?'—<small class="activity-subtitle">固定打码量 '+E(x.recommendedTurnover)+' INR</small>':E(x.wager)+'倍'}</td><td class="mini">${x.basic.terminals.map(t=>terminals[t]).join('、')}</td><td class="mini">${E(D.period(x))}</td><td><span class="state-pill ${enabled?'':'off'}">${D.status(x,bundle)}</span></td><td>${x.updatedAt?'当前管理员':'—'}</td><td class="mini">${E(format(x.updatedAt))}</td><td class="actions-cell"><button data-edit="${E(x.id)}">修改</button><button data-record="${E(x.id)}">记录</button><button data-detail="${E(x.id)}">详情</button><button data-copy="${E(x.id)}">复制</button><button data-toggle="${E(x.id)}">${enabled?'关闭活动':'启用活动'}</button></td></tr>`;}).join('')||'<tr><td colspan="10">没有符合条件的活动</td></tr>';
  $('activityCount').textContent=`共 ${rows.length} 条 · 已启用 ${bundle.selected.length} 项充值活动`;
 }
 function editor(x){document.querySelectorAll('.promotion-only').forEach(e=>e.hidden=true);document.querySelectorAll('.deposit-only').forEach(e=>e.hidden=false);$('rewardTypeField').hidden=false;$('basicLocale').closest('.field').hidden=false;$('activityEditor').classList.remove('promotion-view');draft=R.clone(x);$('activityEditor').classList.remove('awaiting-type');if(draft.type==='first')draft.firstConfig=R.clone(draft.firstConfig||R.defaults);$('editorTitle').textContent=(bundle.items.some(v=>v.id===x.id)?'修改':'新增')+'活动';$('activityType').value='deposit';$('editType').value=D.subtype(draft);$('editType').disabled=bundle.items.some(v=>v.id===x.id);$('wallet').querySelector('[value="现金和彩金钱包"]').disabled=draft.type==='first';ChannelBasic.mount(draft);for(const [id,key] of Object.entries(fields))$(id).value=draft[key]??'';$('activityMethod').disabled=false;const c=D.conditions(draft);$('qualification').value=c.mode;$('qualifyWindow').value=c.window;$('cumulativeMin').value=c.minimum;$('rewardShape').value=c.shape;$('activityBadge').value=draft.badge?'show':'hide';$('editStatus').textContent='';$('saveActivity').disabled=false;FirstRewardEditor.mount(draft.firstConfig||R.defaults,refresh);drawChannels();drawRanges();refresh();if(!$('activityEditor').open)$('activityEditor').showModal();}
 function drawChannels(){const method=$('activityMethod').value;$('activityChannels').innerHTML=D.channels.filter(ch=>method==='all'||method===ch.method||method==='bank'&&ch.method==='other'||method==='other'&&ch.method!=='third').map(ch=>`<label><input type="checkbox" data-target-channel="${ch.id}" ${draft.channels.includes(ch.id)?'checked':''}> ${ch.name}</label>`).join('');}
 function drawRanges(){$('rangeRows').innerHTML=draft.ranges.map((r,i)=>`<tr><td><input data-range="${i}" data-field="min" value="${E(r.min)}" aria-label="区间${i+1}下限"></td><td><input data-range="${i}" data-field="max" value="${E(r.max)}" placeholder="无上限" aria-label="区间${i+1}上限"></td><td><select data-range="${i}" data-field="type" aria-label="区间${i+1}类型"><option value="percent" ${r.type==='percent'?'selected':''}>比例</option><option value="fixed" ${r.type==='fixed'?'selected':''}>金额</option></select></td><td><input data-range="${i}" data-field="value" value="${E(r.value)}" aria-label="区间${i+1}奖励"></td><td><button type="button" data-delete-range="${i}" ${draft.ranges.length===1?'disabled':''}>删除</button></td></tr>`).join('');}
 function capture(){if(draft.promotionView)return draft;Object.assign(draft,ChannelBasic.snapshot());for(const [id,key] of Object.entries(fields))draft[key]=$(id).value;draft.badge=$('activityBadge').value==='show';draft.channels=[...document.querySelectorAll('[data-target-channel]:checked')].map(e=>e.dataset.targetChannel);if(draft.ranges.length){draft.threshold=draft.ranges[0].min;draft.maxAmount='';}draft.dailyCount=undefined;if(draft.type!=='first')draft.conditions={mode:$('qualification').value,window:$('qualifyWindow').value,minimum:$('cumulativeMin').value,shape:$('rewardShape').value};if(draft.type==='first'){draft.firstConfig=FirstRewardEditor.read();draft.firstConfig=D.firstConfig(draft);draft.dailyCap='';draft.claimLimit='1';draft.countPeriod='total';}return draft;}
 function refresh(){if(!draft)return;if(draft.promotionView){Object.assign(draft,ChannelBasic.snapshot());ChannelBasic.update(draft);return;}capture();ChannelBasic.update(draft);const first=draft.type==='first';$('splitRow').hidden=draft.wallet!=='现金和彩金钱包';$('bonusShare').textContent='彩金 '+(100-Number(draft.cashShare||0))+'%';$('firstRewardSection').hidden=!first;$('generalConditions').hidden=first;const c=D.conditions(draft);$('rangeSection').hidden=first||c.shape!=='ranges';$('simpleSection').hidden=first||c.shape==='ranges';$('cumulativeRow').hidden=!['cumulative','both'].includes(c.mode);$('qualifyWindowRow').hidden=$('cumulativeRow').hidden;$('windowHint').textContent=c.window==='rolling7'?'以本笔成功时间往前推168小时，统计此范围内符合方式与通道的成功充值。过期记录自动移出；奖励仍受次数与上限限制。':c.window==='lifetime'?'累计全部符合方式与通道的成功充值，包含活动启用前的历史充值。':c.window==='activity'?'从本活动开始时间累计；始终开启的活动从首次启用时起累计。':'按站点当日统计，次日重新累计。';$('windowHint').hidden=$('cumulativeRow').hidden;$('repeatLimits').hidden=first;$('trialAgeRow').hidden=!first;$('trialPriorRow').hidden=first;$('trialChannelRow').hidden=first;$('rewardSectionTitle').textContent=first?'1. 注册时长与首充金额':'1. 奖励设置';$('turnoverRow').hidden=c.mode!=='exact';$('pointsRow').hidden=!['cumulative','single'].includes(draft.type);$('wagerField').hidden=draft.wallet==='彩金钱包'||c.mode==='exact';$('wagerHint').hidden=draft.wallet==='彩金钱包'||c.mode==='exact';$('rateRow').hidden=draft.rewardMode!=='percent';$('fixedRow').hidden=draft.rewardMode==='percent';$('thresholdLabel').closest('.field').hidden=c.mode==='cumulative';$('thresholdLabel').textContent=c.mode==='exact'?'单次充值金额 =':'单次充值额度 ≥';document.querySelectorAll('[name=walletChoice]').forEach(e=>e.checked=e.value===draft.wallet);$('typeHint').textContent=descriptions[draft.type];trial();}
 function trial(){try{const errors=D.errors(draft);if(errors.length)throw Error(errors[0]);const days=Number($('trialAge').value);if(!Number.isInteger(days)||days<0)throw Error('已注册天数须为非负整数');const ch=draft.type==='first'?D.channels.find(c=>D.applicable(draft,c)):D.channels.find(c=>c.id===$('trialChannel').value);if(!ch)throw Error('当前活动没有适用的充值通道');const event={first:true,registered:new Date(Date.now()-days*86400000).toISOString(),paidAt:new Date().toISOString(),amount:$('trialAmount').value,priorDaily:draft.type==='first'?'0':$('trialPrior').value,channel:ch.method,channelId:ch.id,rewardHistory:{},qualifyingPrior:{[draft.id]:draft.type==='first'?'0':$('trialPrior').value}};const out=H.evaluate(draft.type==='first'?draft.firstConfig:R.load(),{...bundle,items:[draft],selected:[draft.id]},event).items[0];$('trialResult').textContent=out?.state==='eligible'?`预计奖励 ${R.money(out.reward)} INR · 现金 ${R.money(out.cash)} INR／彩金 ${R.money(out.bonus)} INR · 所需打码 ${D.conditions(draft).mode==='exact'?draft.recommendedTurnover:R.money(out.reward*Number(draft.wager))} INR`:'此笔充值不符合当前活动条件。';}catch(e){$('trialResult').textContent=e.message;}}
 function info(x,records=false){$('infoTitle').textContent=x.name['zh-CN']+' · '+(records?'记录':'详情');$('infoBody').innerHTML=records?((x.records||[]).map(r=>`<p>${E(format(r.at))}　${E(r.action)}</p>`).join('')||'<p>暂无操作记录</p>'):`<p>活动类型：充值活动 · ${D.types[x.type]}</p><p>${E(D.summary(x))}</p><p>派奖钱包：${E(D.wallet(x))}</p><p>状态：${D.status(x,bundle)}</p><p>适用通道：${E(x.channels.length?x.channels.map(id=>D.channels.find(c=>c.id===id)?.name||id).join('、'):'所选充值方式的全部通道')}</p><p>活动预算：${E(x.budget)} INR；单用户赠送上限：${x.cap?E(x.cap)+' INR':'无封顶'}</p>`;$('activityInfo').showModal();}
 for(const [k,v] of Object.entries(D.subtypes)){const option=`<option value="${k}">${v}</option>`;$('filterType').insertAdjacentHTML('beforeend',option);$('editType').insertAdjacentHTML('beforeend',option);}$('trialChannel').innerHTML=D.channels.map(ch=>`<option value="${ch.id}">${ch.name}</option>`).join('');
 function showFamily(promotion){draft.promotionView=promotion;$('activityType').value=promotion?'promotion':'deposit';$('activityEditor').classList.toggle('promotion-view',promotion);document.querySelectorAll('.promotion-only').forEach(e=>e.hidden=!promotion);document.querySelectorAll('.deposit-only').forEach(e=>e.hidden=promotion);$('rewardTypeField').hidden=promotion;$('basicLocale').closest('.field').hidden=promotion;$('saveActivity').disabled=promotion;if(promotion){draft.wallet='彩金钱包';draft.basic.terminals=[];draft.basic.startAt='';draft.basic.endAt='';ChannelBasic.mount(draft);$('wallet').value=draft.wallet;document.querySelectorAll('[name=walletChoice]').forEach(e=>e.checked=e.value===draft.wallet);$('wagerField').hidden=$('wagerHint').hidden=$('splitRow').hidden=$('turnoverRow').hidden=true;}else refresh();}
 function addActivity(){editor(D.make('deposit'));showFamily(true);}$('addActivity').onclick=addActivity;$('search').onclick=draw;$('filterFamily').onchange=draw;$('resetFilters').onclick=()=>{for(const id of ['searchName','createdFrom','createdTo'])$(id).value='';$('filterType').value=$('filterStatus').value='all';$('filterFamily').value=view==='deposit'?'deposit':'all';draw();};
 $('editType').onchange=()=>{const next=D.make($('editType').value);if(next.type==='first'){next.firstConfig=R.clone(R.defaults);next.budget=R.defaults.budget;}editor(next);};$('activityType').onchange=()=>{if($('activityType').value==='deposit'){editor(D.make('deposit'));showFamily(false);}else showFamily(true);};$('activityMethod').addEventListener('change',()=>{draft.channels=[];drawChannels();refresh();});
 for(const event of ['input','change'])$('activityEditor').addEventListener(event,e=>{if(e.target.dataset.range!==undefined)draft.ranges[Number(e.target.dataset.range)][e.target.dataset.field]=e.target.value;if(e.target.name==='walletChoice'){$('wallet').value=e.target.value;if(draft.promotionView)draft.wallet=e.target.value;}if(e.target.id==='rewardShape'){if(e.target.value==='simple')draft.ranges=[];else if(!draft.ranges.length)draft.ranges=R.clone(D.make('deposit').ranges);drawRanges();}if(e.target.id==='qualification'&&e.target.value==='exact'){$('rewardShape').value='simple';draft.ranges=[];drawRanges();}if(!['editName','intro','customRules','startAt','endAt','activityType','editType'].includes(e.target.id))refresh();});
 $('addRange').onclick=()=>{const last=draft.ranges.at(-1);if(last&&!last.max)last.max=R.money(R.minor(last.min)+49999);draft.ranges.push({min:last?R.money(R.minor(last.max)+1):'100',max:'',type:'percent',value:'2'});drawRanges();refresh();};
 document.addEventListener('click',e=>{const t=e.target.closest('button');if(!t)return;if(t.dataset.close){$(t.dataset.close).close();return;}if(t.dataset.view){view=t.dataset.view;$('filterFamily').value=view==='deposit'?'deposit':'all';const q=new URLSearchParams(location.search);q.set('tab',view);q.delete('edit');history.replaceState(null,'','?'+q);draw();return;}if(t.dataset.edit)editor(bundle.items.find(x=>x.id===t.dataset.edit));if(t.dataset.detail)info(bundle.items.find(x=>x.id===t.dataset.detail));if(t.dataset.record)info(bundle.items.find(x=>x.id===t.dataset.record),true);
  if(t.dataset.copy){const source=bundle.items.find(x=>x.id===t.dataset.copy),x=R.clone(source);x.id=D.make(x.type).id;x.createdAt=stamp();delete x.closedAt;delete x.updatedAt;x.records=[];x.basic.nameMode='custom';for(const l of Object.keys(x.name))x.name[l]+=(l==='bn'?' (অনুলিপি)':l==='en'?' (copy)':'（副本）');editor(x);}
  if(t.dataset.toggle||t.dataset.pin){try{const next=R.clone(bundle),x=next.items.find(x=>x.id===(t.dataset.toggle||t.dataset.pin));if(t.dataset.pin){x.pinned=!x.pinned;note(x,x.pinned?'置顶':'取消置顶');}else{const enabled=next.selected.includes(x.id);if(!enabled){const errors=D.errors(x);if(errors.length)throw Error(errors.join('；'));delete x.closedAt;if(x.basic.periodMode==='always'&&!x.activatedAt){x.activatedAt=stamp();x.basic.startAt=x.activatedAt;}next.selected.push(x.id);}else{x.closedAt=stamp();next.selected=next.selected.filter(id=>id!==x.id);}note(x,enabled?'关闭活动':'启用活动');}D.save(next);bundle=next;draw();$('listStatus').textContent='已更新。充值设置与通道优惠将读取相同活动状态。';}catch(err){$('listStatus').textContent=err.message;}}
  if(t.dataset.deleteRange!==undefined){draft.ranges.splice(Number(t.dataset.deleteRange),1);drawRanges();refresh();}
 });
 $('addPromotionRow').onclick=()=>{const row=$('promotionRows').rows[0].cloneNode(true);row.querySelector('button').remove();$('promotionRows').append(row);};
 $('saveActivity').onclick=()=>{try{if($('activityType').value!=='deposit')throw Error('请选择活动类型');capture();ChannelBasic.update(draft);Object.assign(draft,ChannelBasic.read());if(draft.type==='first'){draft.firstConfig=D.firstConfig(draft);draft.firstConfig.revision++;}const errors=D.errors(draft);if(errors.length)throw Error(errors.join('\n'));const next=R.clone(bundle),at=next.items.findIndex(x=>x.id===draft.id);draft.createdAt||=stamp();note(draft,at<0?'新增活动':'修改活动');if(at<0)next.items.push(R.clone(draft));else next.items[at]=R.clone(draft);const prior=localStorage.getItem(R.KEY);try{if(draft.id==='registration-first-deposit')localStorage.setItem(R.KEY,JSON.stringify(draft.firstConfig));D.save(next);}catch(err){if(draft.id==='registration-first-deposit'){if(prior===null)localStorage.removeItem(R.KEY);else localStorage.setItem(R.KEY,prior);}throw err;}bundle=next;$('activityEditor').close();draw();$('listStatus').textContent=at<0?'已保存为草稿。启用后，充值设置与适用通道会显示此活动。':'已保存。活动状态保持不变，显示内容已更新。';}catch(err){$('editStatus').textContent=err.message;}};
 window.addEventListener('storage',e=>{if([H.KEY,R.KEY].includes(e.key)&&!$('activityEditor').open){bundle=D.load();draw();}});$('filterFamily').value=view==='deposit'?'deposit':'all';draw();const query=new URLSearchParams(location.search),edit=query.get('edit');if(edit){const x=bundle.items.find(x=>x.id===edit);if(x)editor(x);}if(query.get('new')==='1')addActivity();
})();
