const assert=require('node:assert/strict');const R=require('./engine.js');let n=0;const test=(name,fn)=>{fn();n++;console.log('PASS',name);};const c=()=>R.clone(R.defaults);const ev=(patch={})=>({first:true,registered:'2026-01-23T12:00:00Z',paidAt:'2026-09-23T12:00:00Z',amount:'1000',...patch});
test('default config',()=>assert.deepEqual(R.validate(c()),[]));
test('six month reward',()=>assert.equal(R.calculate(c(),ev()).reward,3500));
test('exact seven days and previous millisecond',()=>{const x=ev({registered:'2026-09-16T12:00:00Z'});assert.equal(R.calculate(c(),x).row,1);x.paidAt='2026-09-23T11:59:59.999Z';assert.equal(R.calculate(c(),x) .row,0);});
test('amount boundary',()=>{assert.equal(R.calculate(c(),ev({amount:'999.99'})).col,1);assert.equal(R.calculate(c(),ev()).col,2);assert.equal(R.calculate(c(),ev({amount:'99.99'})).state,'ineligible');});
test('fixed is not additive',()=>{const x=c();x.cells[4][2]={type:'fixed',value:'20'};assert.equal(R.calculate(x,ev()).reward,2000);});
test('round down and cap',()=>{const x=c();x.cells[4][0].value='1.5';assert.equal(R.calculate(x,ev({amount:'100.01'})).reward,150);x.cap='1';assert.equal(R.calculate(x,ev({amount:'100.01'})).reward,100);});
test('calendar month clamp and leap year',()=>{assert.equal(new Date(R.threshold('2026-01-31T12:00:00Z',{value:1,unit:'m'})).toISOString(),'2026-02-28T12:00:00.000Z');assert.equal(new Date(R.threshold('2024-01-31T12:00:00Z',{value:1,unit:'m'})).toISOString(),'2024-02-29T12:00:00.000Z');});
test('age switch uses first row',()=>{const x=c();x.ageEnabled=false;assert.equal(R.calculate(x,ev({registered:'2026-09-23T12:00:00Z'})).reward,1500);});
test('non first never qualifies',()=>assert.equal(R.calculate(c(),ev({first:false})).state,'notFirst'));
test('cash requires explicit multiple but bonus does not',()=>{const x=c();x.multiple='';assert.ok(R.validate(x).length);x.wallet='bonus';assert.equal(R.validate(x).length,0);assert.equal(R.calculate(x,ev()).turnover,null);});
test('zero explicit multiple is explicit',()=>{const x=c();x.multiple=0;assert.equal(R.calculate(x,ev()).turnover,0);});
test('reject overlapping and unordered ranges',()=>{const x=c();x.bands=['100','100'];assert.ok(R.validate(x).length);const y=c();y.ages[0]={unit:'d',value:31};assert.ok(R.validate(y).length);});
test('reject incomplete locale',()=>{const x=c();x.texts.en.intro='';assert.ok(R.validate(x).length);});
test('invalid import structure is caught',()=>assert.ok(R.validate({schemaVersion:9}).length));
test('exact decimal rejects exponent and negatives',()=>{assert.throws(()=>R.minor('1e3'));assert.throws(()=>R.minor('-1'));assert.throws(()=>R.minor('0.001'));});
test('duplicate settlement and callback conserve funds',()=>{const result=R.calculate(c(),ev());let s={available:10000,reserved:0,spent:0,records:{}};s=R.settle(s,'one',result,ev());s=R.settle(s,'one',result,ev());assert.equal(s.reserved,3500);s=R.callback(s,'one','unknown');assert.equal(s.reserved,3500);s=R.callback(s,'one','failed');assert.equal(s.reserved,3500);s=R.callback(s,'one','posted');s=R.callback(s,'one','posted');assert.equal(s.spent,3500);assert.equal(s.reserved,0);assert.equal(s.available+s.reserved+s.spent,10000);});
test('insufficient funds create no liability',()=>{const s=R.settle({available:1,reserved:0,spent:0,records:{}},'one',R.calculate(c(),ev()),ev());assert.equal(s.last,'budget');assert.equal(Object.keys(s.records).length,0);});
test('before registration rejected',()=>assert.equal(R.calculate(c(),ev({registered:'2027-01-01T00:00:00Z'})).state,'invalid'));
console.log(n+' meaningful engine checks passed');
