const assert=require('node:assert/strict');const R=require('./engine.js'),H=require('./reward-hub.js');const c=()=>R.clone(R.defaults),b=()=>({...H.clone(H.defaults),selected:H.defaults.items.map(x=>x.id)});const e=(x={})=>({amount:'1000',priorDaily:'0',channel:'third',registered:'2026-01-23T12:00:00Z',paidAt:'2026-09-23T12:00:00Z',first:true,...x});
let p=H.evaluate(c(),b(),e());assert.deepEqual(H.validate(b()),[]);assert.equal(p.items.length,5);assert.equal(p.total,7800);assert.deepEqual(p.items.map(x=>x.reward),[3500,1000,500,2000,800]);console.log('PASS five independent demo rewards total 78');
let x=b();x.selected=['registration-first-deposit','daily-single'];p=H.evaluate(c(),x,e());assert.deepEqual(p.items.map(y=>y.id),x.selected);assert.equal(p.total,4000);console.log('PASS backoffice multi-selection controls player result list');
p=H.evaluate(c(),b(),e({channel:'other'}));assert.equal(p.total,5000);assert.equal(p.items.find(y=>y.id==='third-party-gift').state,'ineligible');assert.equal(p.items.find(y=>y.id==='recommended-amount').state,'ineligible');console.log('PASS channel change rechecks both channel rewards');
p=H.evaluate(c(),b(),e({first:false}));assert.equal(p.total,4300);assert.equal(p.items[0].state,'notFirst');console.log('PASS used first deposit does not suppress independent awards');
p=H.evaluate(c(),b(),e({amount:'600',priorDaily:'0'}));assert.equal(p.items.find(y=>y.id==='daily-cumulative').state,'ineligible');assert.equal(p.items.find(y=>y.id==='recommended-amount').state,'ineligible');console.log('PASS daily and exact recommended amount conditions');
p=H.evaluate(c(),b(),e({unknown:true}));assert.equal(p.total,0);assert.equal(p.unknown,5);assert.ok(p.items.every(y=>y.state==='unknown'&&y.reward===null));console.log('PASS unknown is separate from calculable total');
x=b();x.selected.push(x.selected[0]);assert.ok(H.validate(x).length);console.log('PASS duplicate selection rejected');
x=b();x.perOrderLimit='60';p=H.evaluate(c(),x,e());assert.equal(p.total,7800);assert.equal(p.overOrderLimit,true);x.perOrderLimit='100';x.sharedBudget='50';p=H.evaluate(c(),x,e());assert.equal(p.overSharedBudget,true);console.log('PASS aggregate caps expose over-budget sample');
x=b();x.items.find(y=>y.type==='single').threshold='1200';x.items.find(y=>y.type==='cumulative').demoReward='12';p=H.evaluate(c(),x,e());assert.equal(p.items.find(y=>y.id==='daily-single').state,'ineligible');assert.equal(p.items.find(y=>y.id==='daily-cumulative').reward,1200);console.log('PASS task editor values drive qualification and reward');
x=b();x.items.find(y=>y.type==='channel').rate='3';p=H.evaluate(c(),x,e());assert.equal(p.items.find(y=>y.id==='third-party-gift').reward,3000);x.items.find(y=>y.type==='channel').maxAmount='1000';p=H.evaluate(c(),x,e());assert.equal(p.items.find(y=>y.id==='third-party-gift').state,'ineligible');console.log('PASS channel percentage and exclusive upper boundary');
x=b();x.items.find(y=>y.type==='channel').source='旧充值来源';global.localStorage={getItem:()=>JSON.stringify(x)};assert.equal(H.load().items.find(y=>y.type==='channel').source,'活动中心 · 充值奖励');delete global.localStorage;console.log('PASS old local selection shows current ownership label');

assert.deepEqual(H.defaults.selected,['registration-first-deposit']);assert.equal(H.evaluate(c(),H.clone(H.defaults),e()).total,3500);console.log('PASS default starts with first deposit only');
x=b();p=H.evaluate(c(),x,e({rewardHistory:{'third-party-gift':{paid:'99',count:0}}}));assert.equal(p.items.find(y=>y.id==='third-party-gift').reward,100);p=H.evaluate(c(),x,e({rewardHistory:{'third-party-gift':{paid:'0',count:1}}}));assert.equal(p.items.find(y=>y.id==='third-party-gift').state,'ineligible');console.log('PASS daily channel amount and count caps');
