const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),assert=require('node:assert/strict');
const {JSDOM}=require('jsdom');
const root=__dirname;let n=0;
function page(name,search=''){
 const dom=new JSDOM(fs.readFileSync(path.join(root,name),'utf8'),{url:'https://prototype.invalid/'+name+search,runScripts:'outside-only'});
 dom.window.HTMLElement.prototype.scrollIntoView=function(){};
 for(const script of dom.window.document.querySelectorAll('script[src]'))vm.runInContext(fs.readFileSync(path.join(root,script.getAttribute('src')),'utf8'),dom.getInternalVMContext(),{filename:script.getAttribute('src')});
 return dom;
}
function check(name,fn){fn();n++;console.log('PASS',name);}
function set(w,id,value,event='input'){const e=w.document.getElementById(id);assert.ok(e,id);e.value=value;e.dispatchEvent(new w.Event(event,{bubbles:true}));}
check('all delivery pages load and have no development copy',()=>{for(const f of ['index.html','rewards.html','deposit-settings.html','task-center.html','channel-rewards.html','player.html','deposit.html','guide.html','presentation.html']){const d=page(f);assert.doesNotMatch(d.window.document.body.textContent,/本地|原型|演示|示例|版本|debug|DEMO|待映射|测试站|prompt/i);d.window.close();}});
check('new member can compare three genuine amount rewards',()=>{const d=page('player.html'),w=d.window;assert.match(w.document.getElementById('estimate').textContent,/0.50 INR/);w.document.querySelectorAll('.tier-choice')[2].click();assert.match(w.document.getElementById('estimate').textContent,/15.00 INR/);set(w,'locale','zh-TW','change');assert.equal(w.document.getElementById('title').textContent,'首充成長階梯');assert.equal(w.document.getElementById('primary').textContent,'前往充值');set(w,'locale','en','change');assert.equal(w.document.getElementById('rulesTitle').textContent,'How it works');d.window.close();});
check('returning member amount bands and cap',()=>{const d=page('player.html','?scenario=returning'),w=d.window;assert.match(w.document.getElementById('estimate').textContent,/35.00 INR/);set(w,'amountInput','100000');assert.match(w.document.getElementById('estimate').textContent,/100.00 INR/);assert.equal(w.document.getElementById('nextGoal').textContent,'已达到当前可得奖励上限');d.window.close();});
check('used first deposit has no next reward invitation',()=>{const d=page('player.html','?scenario=used'),w=d.window;assert.equal(w.document.getElementById('stage').hidden,true);assert.equal(w.document.getElementById('nextGoal').textContent,'');assert.match(w.document.getElementById('status').textContent,/限一次/);d.window.close();});
check('pending order freezes amount and can be cancelled',()=>{const d=page('deposit.html'),w=d.window;w.document.getElementById('primary').click();assert.equal(w.document.getElementById('amountInput').disabled,true);assert.equal(w.document.getElementById('resultTitle').textContent,'等待支付结果');w.document.getElementById('cancel').click();assert.equal(w.document.getElementById('amountInput').disabled,false);d.window.close();});
check('unknown result is not presented as zero or credited',()=>{const d=page('deposit.html','?scenario=unknown'),w=d.window;assert.equal(w.document.getElementById('total').textContent,'正在核验');assert.equal(w.document.getElementById('primary').hidden,true);assert.equal(w.document.getElementById('resultTitle').textContent,'正在确认奖励');d.window.close();});
check('recommended first deposit settings save without manual field setup',()=>{const d=page('index.html'),w=d.window;w.document.getElementById('save').click();const c=JSON.parse(w.localStorage.getItem(w.Reward.KEY));assert.ok(c);assert.deepEqual(c.bands,['100','500','1000']);assert.ok(c.basic.startAt&&c.basic.endAt);assert.equal(c.cap,'100');set(w,'cap','55');w.document.getElementById('restorePreset').click();assert.equal(w.document.getElementById('cap').value,'100');d.window.close();});
check('channel activity keeps full basic fields and saves reward rules',()=>{const d=page('channel-rewards.html','?edit=third-party-gift'),w=d.window;assert.equal(w.document.getElementById('editor').hidden,false);set(w,'rate','3');assert.match(w.document.getElementById('previewRules').textContent,/3%/);w.document.getElementById('saveEdit').click();const b=JSON.parse(w.localStorage.getItem(w.RewardHub.KEY));assert.ok(b);const x=b.items.find(x=>x.type==='channel');assert.equal(x.rate,'3');assert.ok(x.basic.startAt);assert.equal(x.basic.terminals.length,4);d.window.close();});
check('task editor saves its own reward and payment method',()=>{const d=page('task-center.html','?edit=daily-single'),w=d.window;set(w,'reward','7');set(w,'taskMethod','third','change');w.document.getElementById('saveEdit').click();const x=JSON.parse(w.localStorage.getItem(w.RewardHub.KEY)).items.find(x=>x.type==='single');assert.equal(x.demoReward,'7');assert.equal(x.method,'third');d.window.close();});
check('channel system copy follows language, type and wallet',()=>{const d=page('channel-rewards.html','?edit=third-party-gift'),w=d.window;set(w,'basicLocale','zh-TW','change');set(w,'editType','recommended-amount','change');assert.equal(w.document.getElementById('editName').value,'通道推薦金額加贈');set(w,'wallet','现金钱包');set(w,'wager','2');assert.match(w.document.getElementById('previewRules').textContent,/獎勵金額 × 2倍/);set(w,'basicLocale','en','change');assert.doesNotMatch(w.document.getElementById('previewRules').textContent,/[\u3400-\u9fff]/);d.window.close();});
check('reward selection stays in activity center',()=>{const d=page('rewards.html'),w=d.window;assert.equal(w.document.querySelectorAll('[data-select]:checked').length,1);const e=w.document.querySelector('[data-select="daily-cumulative"]');e.checked=true;e.dispatchEvent(new w.Event('change',{bubbles:true}));w.document.getElementById('save').click();assert.equal(JSON.parse(w.localStorage.getItem(w.RewardHub.KEY)).selected.length,2);d.window.close();});
check('deposit overview contains no reward mutation controls',()=>{const d=page('deposit-settings.html'),w=d.window;assert.equal(w.document.querySelectorAll('input,select').length,0);assert.equal(w.localStorage.length,0);w.document.querySelector('[data-channel="bank"]').click();assert.equal(w.document.querySelectorAll('#promotionRows tr').length,3);assert.equal(w.localStorage.length,0);d.window.close();});
check('presentation navigation and shared example stay consistent',()=>{const d=page('presentation.html'),w=d.window;assert.equal(w.document.querySelectorAll('.slide').length,14);assert.match(w.document.getElementById('slides').textContent,/78.00 INR/);w.document.getElementById('next').click();assert.equal(w.location.hash,'#page-2');set(w,'toc','10','change');assert.equal(w.location.hash,'#page-11');d.window.close();});
check('future reward preview never replaces today reward',()=>{const d=page('player.html','?scenario=near&amount=500'),w=d.window;assert.match(w.document.getElementById('estimate').textContent,/7.50 INR/);set(w,'futureDays','20');assert.match(w.document.getElementById('forecastResult').textContent,/10.00 INR/);assert.match(w.document.getElementById('estimate').textContent,/7.50 INR/);assert.match(w.document.getElementById('nextGoal').textContent,/500.00 INR/);assert.match(w.document.getElementById('nextGoal').textContent,/12.50 INR/);set(w,'futureDays','500');assert.match(w.document.getElementById('forecastResult').textContent,/不在活动期间/);set(w,'futureDays','-1');assert.match(w.document.getElementById('forecastResult').textContent,/整数天数/);d.window.close();});
check('progress distinguishes reached age and completed first deposit',()=>{const d=page('player.html','?scenario=credited'),w=d.window;assert.equal(w.document.getElementById('futurePanel').hidden,true);assert.match(w.document.getElementById('completionNote').textContent,/已完成奖励档位/);assert.ok(w.document.querySelectorAll('.age-steps .passed').length);assert.equal(w.document.getElementById('stage').hidden,true);d.window.close();});
check('future preview and page labels follow language',()=>{const d=page('player.html'),w=d.window;set(w,'locale','en','change');assert.doesNotMatch(w.document.getElementById('futurePanel').textContent,/[㐀-鿿]/);assert.doesNotMatch(w.document.querySelector('.page-navigation').textContent,/[㐀-鿿]/);set(w,'locale','zh-TW','change');assert.match(w.document.getElementById('futureTitle').textContent,/預覽未來優惠/);assert.match(w.document.getElementById('ageLabel').textContent,/已註冊/);d.window.close();});
check('budget fields live in basic info and navigation is outside main',()=>{const d=page('index.html'),w=d.window;for(const id of ['wallet','multiple','cap','budget'])assert.ok(w.document.getElementById('basic').contains(w.document.getElementById(id)));assert.equal(w.document.querySelector('main .page-navigation'),null);assert.equal(w.document.querySelector('.page-navigation').parentElement,w.document.body);assert.doesNotMatch(w.document.body.textContent,/日历月|资金承诺机制/);assert.match(w.document.getElementById('basic').textContent,/无封顶也不会超过总体活动预算/);d.window.close();});
console.log(n+' DOM checks passed; this does not verify browser layout or live payment services.');
