const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),assert=require('node:assert/strict');
const {JSDOM}=require('jsdom');
const root=__dirname;let n=0;
function page(name,search='',seed={}){
 const dom=new JSDOM(fs.readFileSync(path.join(root,name),'utf8'),{url:'https://prototype.invalid/'+name+search,runScripts:'outside-only'});
 dom.window.HTMLElement.prototype.scrollIntoView=function(){};
 dom.window.HTMLDialogElement.prototype.showModal=function(){this.open=true;};dom.window.HTMLDialogElement.prototype.close=function(){this.open=false;};
 for(const [k,v] of Object.entries(seed))dom.window.localStorage.setItem(k,typeof v==='string'?v:JSON.stringify(v));
 for(const script of dom.window.document.querySelectorAll('script[src]'))vm.runInContext(fs.readFileSync(path.join(root,script.getAttribute('src').split('?')[0]),'utf8'),dom.getInternalVMContext(),{filename:script.getAttribute('src')});
 return dom;
}
function check(name,fn){fn();n++;console.log('PASS',name);}
check('rule table identifies both axes and uses compact exclusive ranges',()=>{const d=page('player.html'),w=d.window;const corner=w.document.querySelector('.rule-axes');assert.match(corner.textContent,/充值金额/);assert.match(corner.textContent,/注册时长/);assert.equal(w.document.querySelector('.reward-rules tbody th').textContent,'0~7日');assert.match(w.document.getElementById('table').textContent,/7日~1月/);assert.match(w.document.getElementById('table').textContent,/不含上限/);assert.doesNotMatch(w.document.getElementById('table').textContent,/至不足|个月/);d.window.close();});
check('Bengali covers both player views and all fourteen participation states',()=>{for(const file of ['player.html','deposit.html']){for(const scenario of ['new','login','notstarted','ended','paused','blocked','unmet','used','limit','pending','unknown','rewardpending','rewardfailed','credited']){const d=page(file,'?lang=bn&scenario='+scenario),w=d.window;assert.equal(w.document.documentElement.lang,'bn');assert.match(w.document.title,/[\u0980-\u09ff]/);assert.doesNotMatch(w.document.querySelector('main').textContent.replace(w.document.getElementById('locale').textContent,''),/[\u3400-\u9fff]|undefined|NaN|Invalid Date/);assert.match(w.document.getElementById('resultTitle').textContent,/[\u0980-\u09ff]/);assert.match(w.document.getElementById('rules').textContent,/[\u0980-\u09ff]/);assert.match(w.document.getElementById('table').textContent,/0~7 দিন/);set(w,'locale','en','change');assert.equal(w.document.documentElement.lang,'en');set(w,'locale','bn','change');assert.equal(new URL(w.location.href).searchParams.get('lang'),'bn');d.window.close();}}});
check('old saved settings gain Bengali without replacing custom values',()=>{const seed=page('player.html'),R=seed.window.Reward,c=R.clone(R.defaults);delete c.texts.bn;c.cap='88';c.texts.en.name='Custom title';const d=page('player.html','?lang=bn',{[R.KEY]:c});assert.equal(d.window.Reward.load().cap,'88');assert.equal(d.window.Reward.load().texts.en.name,'Custom title');assert.match(d.window.document.getElementById('title').textContent,/[\u0980-\u09ff]/);d.window.close();c.texts.bn={name:'আমার অফার',intro:'আমার বোনাস'};const b=page('player.html','?lang=bn',{[R.KEY]:c});assert.equal(b.window.document.getElementById('title').textContent,'আমার অফার');b.window.close();seed.window.close();});
check('developer tools share language and scenario in both preview links',()=>{const d=page('developer-tools.html'),w=d.window;set(w,'previewLanguage','bn','change');set(w,'previewState','credited','change');for(const id of ['activityPreview','depositPreview']){const u=new URL(w.document.getElementById(id).href);assert.equal(u.searchParams.get('lang'),'bn');assert.equal(u.searchParams.get('scenario'),'credited');}assert.match(w.document.getElementById('stateDescription').textContent,/[\u0980-\u09ff]/);assert.equal(w.localStorage.length,0);d.window.close();});
check('first deposit system copy and saved Bengali follow the editor locale',()=>{const d=page('index.html','?edit=registration-first-deposit'),w=d.window;set(w,'basicLocale','bn','change');for(const id of ['editName','intro','previewRules'])assert.match(w.document.getElementById(id).value||w.document.getElementById(id).textContent,/[\u0980-\u09ff]/);w.document.getElementById('saveActivity').click();const c=JSON.parse(w.localStorage.getItem(w.Reward.KEY));assert.ok(c,w.document.getElementById('editStatus').textContent);assert.match(c.texts.bn.name,/[\u0980-\u09ff]/);assert.match(c.texts.bn.intro,/[\u0980-\u09ff]/);d.window.close();});
check('general recharge scope note is visible across management and presentation',()=>{for(const file of ['index.html','guide.html','deposit-guide.html','presentation.html','deposit-plan.html','deposit-settings.html']){const d=page(file);assert.match(d.window.document.querySelector('.scope-note').textContent,/通用充值回馈：此次不进行/);d.window.close();}});
function set(w,id,value,event='input'){const e=w.document.getElementById(id);assert.ok(e,id);e.value=value;e.dispatchEvent(new w.Event(event,{bubbles:true}));}
check('all delivery pages load and have no development copy',()=>{for(const f of ['index.html','rewards.html','deposit-settings.html','task-center.html','channel-rewards.html','player.html','deposit.html','guide.html','presentation.html','deposit-plan.html','deposit-guide.html']){const d=page(f);assert.doesNotMatch(d.window.document.body.textContent,/本地|原型|演示|示例|版本|debug|DEMO|待映射|测试站|prompt/i);d.window.close();}});
check('new member can compare three genuine amount rewards',()=>{const d=page('player.html'),w=d.window;assert.match(w.document.getElementById('estimate').textContent,/0.50 INR/);w.document.querySelectorAll('.tier-choice')[2].click();assert.match(w.document.getElementById('estimate').textContent,/15.00 INR/);set(w,'locale','zh-TW','change');assert.equal(w.document.getElementById('title').textContent,'首充成長階梯');assert.equal(w.document.getElementById('primary').textContent,'前往充值');set(w,'locale','en','change');assert.equal(w.document.getElementById('rulesTitle').textContent,'How it works');d.window.close();});
check('returning member amount bands and cap',()=>{const d=page('player.html','?scenario=returning'),w=d.window;assert.match(w.document.getElementById('estimate').textContent,/35.00 INR/);set(w,'amountInput','100000');assert.match(w.document.getElementById('estimate').textContent,/100.00 INR/);assert.equal(w.document.getElementById('nextGoal').textContent,'已达到当前可得奖励上限');d.window.close();});
check('used first deposit has no next reward invitation',()=>{const d=page('player.html','?scenario=used'),w=d.window;assert.equal(w.document.getElementById('stage').hidden,true);assert.equal(w.document.getElementById('nextGoal').textContent,'');assert.match(w.document.getElementById('status').textContent,/限一次/);d.window.close();});
check('pending order freezes amount and can be cancelled',()=>{const d=page('deposit.html'),w=d.window;w.document.getElementById('primary').click();assert.equal(w.document.getElementById('amountInput').disabled,true);assert.equal(w.document.getElementById('resultTitle').textContent,'等待支付结果');w.document.getElementById('cancel').click();assert.equal(w.document.getElementById('amountInput').disabled,false);d.window.close();});
check('unknown result is not presented as zero or credited',()=>{const d=page('deposit.html','?scenario=unknown'),w=d.window;assert.equal(w.document.getElementById('total').textContent,'正在核验');assert.equal(w.document.getElementById('primary').hidden,true);assert.equal(w.document.getElementById('resultTitle').textContent,'正在核验');d.window.close();});
check('first deposit is editable inside the same activity dialog',()=>{const d=page('index.html','?edit=registration-first-deposit'),w=d.window;assert.equal(w.document.getElementById('firstRewardSection').hidden,false);assert.equal(w.document.getElementById('editType').value,'first');set(w,'activityCap','55');w.document.getElementById('saveActivity').click();const c=JSON.parse(w.localStorage.getItem(w.Reward.KEY));assert.ok(c,w.document.getElementById('editStatus').textContent);assert.deepEqual(c.bands,['100','500','1000']);assert.ok(c.basic.startAt&&c.basic.endAt);assert.equal(c.cap,'55');d.window.close();});
check('budget page cannot change activity activation',()=>{const d=page('rewards.html'),w=d.window;assert.equal(w.document.querySelectorAll('[data-select]').length,0);assert.equal(w.document.querySelectorAll('#catalogue tr').length,1);set(w,'sharedBudget','20000');w.document.getElementById('save').click();const b=JSON.parse(w.localStorage.getItem(w.RewardHub.KEY));assert.deepEqual(b.selected,['registration-first-deposit']);assert.equal(b.sharedBudget,'20000');d.window.close();});
check('presentation navigation and shared example stay consistent',()=>{const d=page('presentation.html'),w=d.window;assert.equal(w.document.querySelectorAll('.slide').length,14);assert.match(w.document.getElementById('slides').textContent,/78.00 INR/);w.document.getElementById('next').click();assert.equal(w.location.hash,'#page-2');set(w,'toc','10','change');assert.equal(w.location.hash,'#page-11');d.window.close();});
check('future reward preview never replaces today reward',()=>{const d=page('player.html','?scenario=near&amount=500'),w=d.window;assert.match(w.document.getElementById('estimate').textContent,/7.50 INR/);set(w,'futureDays','20');assert.match(w.document.getElementById('forecastResult').textContent,/10.00 INR/);assert.match(w.document.getElementById('estimate').textContent,/7.50 INR/);assert.match(w.document.getElementById('nextGoal').textContent,/500.00 INR/);assert.match(w.document.getElementById('nextGoal').textContent,/12.50 INR/);set(w,'futureDays','500');assert.match(w.document.getElementById('forecastResult').textContent,/不在活动期间/);set(w,'futureDays','-1');assert.match(w.document.getElementById('forecastResult').textContent,/整数天数/);d.window.close();});
check('progress distinguishes reached age and completed first deposit',()=>{const d=page('player.html','?scenario=credited'),w=d.window;assert.equal(w.document.getElementById('futurePanel').hidden,true);assert.match(w.document.getElementById('completionNote').textContent,/已完成奖励档位/);assert.ok(w.document.querySelectorAll('.age-steps .passed').length);assert.equal(w.document.getElementById('stage').hidden,true);d.window.close();});
check('future preview and page labels follow language',()=>{const d=page('player.html'),w=d.window;set(w,'locale','en','change');assert.doesNotMatch(w.document.getElementById('futurePanel').textContent,/[㐀-鿿]/);assert.doesNotMatch(w.document.querySelector('.page-navigation').textContent,/[㐀-鿿]/);set(w,'locale','zh-TW','change');assert.match(w.document.getElementById('futureTitle').textContent,/預覽未來優惠/);assert.match(w.document.getElementById('ageLabel').textContent,/已註冊/);d.window.close();});
check('budget fields live in basic info and navigation is outside main',()=>{const d=page('index.html'),w=d.window;for(const id of ['wallet','wager','activityCap','activityBudget'])assert.ok(w.document.getElementById('basic').contains(w.document.getElementById(id)));assert.equal(w.document.querySelector('main .page-navigation'),null);assert.equal(w.document.querySelector('.page-navigation').parentElement,w.document.body);assert.doesNotMatch(w.document.body.textContent,/日历月|资金承诺机制/);assert.match(w.document.getElementById('basic').textContent,/无封顶也不会超过总体活动预算/);d.window.close();});


check('central editor retains full basic fields and saves inclusive channel ranges',()=>{
 const d=page('index.html','?edit=third-party-gift'),w=d.window;
 assert.equal(w.document.getElementById('activityEditor').open,true);
 for(const id of ['startAt','endAt','ipLimit','deviceLimit','wallet','wager','activityBudget','activityCap','intro','previewRules','layout','background','icon','showText','activityIntro'])if(id!=='showText')assert.ok(w.document.getElementById(id),id);
 const e=w.document.querySelector('[data-range="0"][data-field="value"]');e.value='3';e.dispatchEvent(new w.Event('input',{bubbles:true}));
 assert.match(w.document.getElementById('previewRules').textContent,/3%/);
 w.document.getElementById('saveActivity').click();const b=JSON.parse(w.localStorage.getItem(w.RewardHub.KEY));assert.ok(b,w.document.getElementById('editStatus').textContent);const x=b.items.find(x=>x.type==='channel');assert.equal(x.ranges[0].value,'3');assert.equal(x.ranges[0].max,'4999.99');assert.equal(x.basic.terminals.length,4);d.window.close();
});
let sharedSeed;
check('new deposit activity saves split wallets, lifetime limit and bank scope',()=>{
 const d=page('index.html'),w=d.window;w.document.getElementById('addActivity').click();set(w,'activityType','deposit','change');
 set(w,'wallet','现金和彩金钱包','change');assert.equal(w.document.getElementById('splitRow').hidden,false);
 assert.match(w.document.getElementById('trialResult').textContent,/现金 10.00 INR／彩金 10.00 INR/);
 set(w,'countPeriod','total','change');set(w,'claimLimit','3');set(w,'activityMethod','bank','change');set(w,'trialChannel','bank','change');
 assert.match(w.document.getElementById('trialResult').textContent,/20.00 INR/);
 w.document.getElementById('saveActivity').click();const saved=JSON.parse(w.localStorage.getItem(w.RewardHub.KEY));assert.ok(saved,w.document.getElementById('editStatus').textContent);assert.equal(saved.selected.includes(saved.items.at(-1).id),false);w.document.querySelector('[data-toggle="'+saved.items.at(-1).id+'"]').click();
 const raw=w.localStorage.getItem(w.RewardHub.KEY);assert.ok(raw,w.document.getElementById('editStatus').textContent);sharedSeed={[w.RewardHub.KEY]:raw};const b=JSON.parse(raw),x=b.items.at(-1);assert.equal(x.wallet,'现金和彩金钱包');assert.equal(x.claimLimit,'3');assert.equal(x.countPeriod,'total');assert.equal(x.method,'bank');assert.ok(b.selected.includes(x.id));assert.equal(w.document.getElementById('activityEditor').open,false);d.window.close();
});
check('finance popup reads enabled activity and saves payment settings only',()=>{
 const d=page('deposit-settings.html','?settings=open',sharedSeed),w=d.window;assert.equal(w.document.getElementById('financeSettings').open,true);
 const before=w.localStorage.getItem(w.RewardHub.KEY);assert.equal(w.document.querySelectorAll('#enabledActivities tr').length,2);assert.match(w.document.getElementById('enabledActivities').textContent,/现金 50%／彩金 50%/);
 assert.equal(w.document.querySelectorAll('.rewards-readonly input,.rewards-readonly select').length,0);
 set(w,'orderMinutes','45');w.document.getElementById('saveFinance').click();assert.equal(JSON.parse(w.localStorage.getItem('ngss3.deposit-payment-settings')).orderMinutes,'45');assert.equal(w.localStorage.getItem(w.RewardHub.KEY),before);
 assert.equal(w.document.querySelectorAll('#promotionRows tr').length,1);w.document.querySelector('[data-method="other"]').click();assert.equal(w.document.querySelectorAll('#promotionRows tr').length,2);d.window.close();
});
check('old channel and task pages only link to the central editor',()=>{for(const name of ['channel-rewards.html','task-center.html']){const d=page(name),w=d.window;assert.equal(w.document.querySelectorAll('input,select').length,0);assert.equal(w.document.getElementById('saveEdit'),null);assert.ok(w.document.querySelector('a[href^="index.html?tab=deposit&edit="]'));assert.equal(w.localStorage.length,0);d.window.close();}});
check('central task settings persist method, reward and activity points',()=>{const d=page('index.html','?edit=daily-single'),w=d.window;set(w,'reward','7');set(w,'activityMethod','third','change');set(w,'taskPoints','5');w.document.getElementById('saveActivity').click();const b=JSON.parse(w.localStorage.getItem(w.RewardHub.KEY));assert.ok(b,w.document.getElementById('editStatus').textContent);const x=b.items.find(x=>x.type==='single');assert.equal(x.demoReward,'7');assert.equal(x.method,'third');assert.equal(x.points,'5');d.window.close();});
check('all central templates provide system copy in three languages',()=>{
 const d=page('index.html'),w=d.window;
 for(const type of ['first','deposit']){w.document.getElementById('addActivity').click();set(w,'activityType','deposit','change');set(w,'editType',type,'change');for(const locale of ['zh-CN','zh-TW','en']){set(w,'basicLocale',locale,'change');assert.ok(w.document.getElementById('editName').value);assert.ok(w.document.getElementById('intro').value);const rule=w.document.getElementById('previewRules').textContent;assert.ok(rule);if(locale==='en')assert.doesNotMatch(rule,/[\u3400-\u9fff]/);}w.document.getElementById('activityEditor').close();}d.window.close();
});
check('invalid split or overlapping range cannot save',()=>{const d=page('index.html'),w=d.window;w.document.getElementById('addActivity').click();set(w,'activityType','deposit','change');set(w,'wallet','现金和彩金钱包','change');set(w,'cashShare','100');w.document.getElementById('saveActivity').click();assert.match(w.document.getElementById('editStatus').textContent,/分配比例/);assert.equal(w.localStorage.length,0);set(w,'cashShare','50');const e=w.document.querySelector('[data-range="1"][data-field="min"]');e.value='499.99';e.dispatchEvent(new w.Event('input',{bubbles:true}));w.document.getElementById('saveActivity').click();assert.match(w.document.getElementById('editStatus').textContent,/不重叠/);assert.equal(w.localStorage.length,0);d.window.close();});
check('new central plan and guide share rules, navigation and exact wallet example',()=>{const d=page('deposit-plan.html'),w=d.window;assert.equal(w.document.querySelectorAll('.slide').length,13);assert.match(w.document.getElementById('slides').textContent,/现金 10.00 INR，彩金 10.00 INR/);w.document.getElementById('next').click();assert.equal(w.location.hash,'#page-2');w.document.dispatchEvent(new w.KeyboardEvent('keydown',{key:'ArrowRight',bubbles:true}));assert.equal(w.location.hash,'#page-3');const g=page('deposit-guide.html');assert.match(g.window.document.getElementById('split').textContent,/现金 10.00 INR，彩金 10.00 INR/);assert.equal(g.window.document.querySelector('.page-navigation').parentElement,g.window.document.body);d.window.close();g.window.close();});


check('all and deposit tabs share the same records and activity editor',()=>{const d=page('index.html'),w=d.window;assert.equal(w.document.getElementById('allActivities').getAttribute('aria-selected'),'true');const ids=[...w.document.querySelectorAll('[data-activity]')].map(e=>e.dataset.activity);w.document.getElementById('depositActivities').click();assert.equal(w.document.getElementById('depositActivities').getAttribute('aria-selected'),'true');assert.deepEqual([...w.document.querySelectorAll('[data-activity]')].map(e=>e.dataset.activity),ids);assert.equal(w.document.getElementById('budgetEntry').hidden,false);w.document.getElementById('addActivity').click();set(w,'activityType','deposit','change');assert.equal(w.document.getElementById('activityType').value,'deposit');assert.equal(w.document.getElementById('editType').options.length,2);assert.equal(w.document.getElementById('templateDialog'),null);d.window.close();});
check('closing an activity removes only that offer from finance popup',()=>{const d=page('index.html','',sharedSeed),w=d.window;const before=JSON.parse(w.localStorage.getItem(w.RewardHub.KEY));const id=before.items.at(-1).id;w.document.querySelector('[data-toggle="'+id+'"]').click();const b=JSON.parse(w.localStorage.getItem(w.RewardHub.KEY));assert.equal(b.selected.includes(id),false);assert.ok(b.selected.includes('registration-first-deposit'));assert.match(w.document.querySelector('[data-activity="'+id+'"]').textContent,/已关闭/);const f=page('deposit-settings.html','?settings=open',{[w.RewardHub.KEY]:b});assert.equal(f.window.document.querySelectorAll('#enabledActivities tr').length,1);assert.equal(w.document.querySelectorAll('[data-activity]').length,b.items.length);d.window.close();f.window.close();});
check('copying an activity creates a separate draft without changing its source',()=>{const d=page('index.html'),w=d.window;w.document.querySelector('[data-copy="recommended-amount"]').click();w.document.getElementById('saveActivity').click();const b=JSON.parse(w.localStorage.getItem(w.RewardHub.KEY));assert.ok(b,w.document.getElementById('editStatus').textContent);assert.equal(b.items.filter(x=>x.type==='recommended').length,2);const x=b.items.at(-1);assert.match(x.name['zh-CN'],/副本/);assert.equal(b.selected.includes(x.id),false);w.document.querySelector('[data-record="'+x.id+'"]').click();assert.match(w.document.getElementById('infoBody').textContent,/新增活动/);d.window.close();});
check('guide explains the integrated flow and compares six offers without saving',()=>{const d=page('guide.html'),w=d.window;for(const id of ['setup-center','multiple-activities','deposit-display','multiple-preview'])assert.ok(w.document.getElementById(id));assert.equal(w.document.querySelectorAll('#exampleResults tbody tr').length,6);assert.match(w.document.getElementById('exampleTotal').textContent,/78.00 INR/);set(w,'exampleChannel','bank','change');assert.match(w.document.getElementById('exampleTotal').textContent,/80.00 INR/);set(w,'exampleChannel','virtual','change');assert.match(w.document.getElementById('exampleTotal').textContent,/50.00 INR/);set(w,'exampleAmount','invalid');assert.equal(w.document.getElementById('exampleTotal').textContent,'');assert.equal(w.localStorage.length,0);d.window.close();});
check('new first-deposit activities retain independent matrices',()=>{const d=page('index.html'),w=d.window;w.document.getElementById('addActivity').click();set(w,'activityType','deposit','change');set(w,'editType','first','change');const v=w.document.querySelector('[data-first-value="0,0"]');v.value='2';v.dispatchEvent(new w.Event('input',{bubbles:true}));w.document.getElementById('saveActivity').click();const b=JSON.parse(w.localStorage.getItem(w.RewardHub.KEY));assert.ok(b,w.document.getElementById('editStatus').textContent);const x=b.items.at(-1);assert.equal(x.firstConfig.cells[0][0].value,'2');assert.equal(w.localStorage.getItem(w.Reward.KEY),null);const first=b.items.find(i=>i.id==='registration-first-deposit');assert.equal(first.firstConfig.cells[0][0].value,'0.5');d.window.close();});
check('new activity opens promotion then switches to only two deposit subtypes',()=>{const d=page('index.html'),w=d.window;w.document.getElementById('addActivity').click();assert.equal(w.document.getElementById('activityType').value,'promotion');assert.equal(w.document.getElementById('editName').value,'推荐好友开宝箱');assert.equal(w.document.getElementById('rewardTypeField').hidden,true);assert.equal(w.document.getElementById('promotionRewards').hidden,false);set(w,'activityType','deposit','change');assert.equal(w.document.getElementById('saveActivity').disabled,false);assert.equal(w.document.getElementById('promotionRewards').hidden,true);assert.deepEqual([...w.document.getElementById('editType').options].map(o=>o.textContent),['首充成长阶梯','通用充值赠送']);d.window.close();});
check('rolling qualification and permanent activity survive editor save and finance reload',()=>{const d=page('index.html'),w=d.window;w.document.getElementById('addActivity').click();set(w,'activityType','deposit','change');set(w,'qualification','both','change');set(w,'qualifyWindow','rolling7','change');set(w,'cumulativeMin','1000');set(w,'trialPrior','500');set(w,'trialAmount','500');assert.match(w.document.getElementById('trialResult').textContent,/7.50 INR/);set(w,'periodMode','always','input');assert.equal(w.document.getElementById('activityDates').hidden,true);set(w,'basicLocale','en','change');assert.match(w.document.getElementById('previewRules').textContent,/rolling last 7 days/);assert.doesNotMatch(w.document.getElementById('previewRules').textContent,/[\u3400-\u9fff]/);w.document.getElementById('saveActivity').click();let b=JSON.parse(w.localStorage.getItem(w.RewardHub.KEY));assert.ok(b,w.document.getElementById('editStatus').textContent);const x=b.items.at(-1);assert.equal(x.conditions.window,'rolling7');assert.equal(x.basic.periodMode,'always');w.document.querySelector('[data-toggle="'+x.id+'"]').click();b=JSON.parse(w.localStorage.getItem(w.RewardHub.KEY));assert.ok(b.items.at(-1).activatedAt);const f=page('deposit-settings.html','?settings=open',{[w.RewardHub.KEY]:b});assert.match(f.window.document.getElementById('enabledActivities').textContent,/始终开启/);assert.match(f.window.document.getElementById('enabledActivities').textContent,/最近7日/);d.window.close();f.window.close();});
check('finance retains original non-moved controls and removes editable gift cap and wallet',()=>{const d=page('deposit-settings.html','?settings=open'),w=d.window;for(const id of ['depositWager','orderMinutes','depositBadge','requestFrequency','clearTurnover','releaseAmount'])assert.ok(w.document.getElementById(id));assert.equal(w.document.querySelectorAll('.rewards-readonly input,.rewards-readonly select').length,0);set(w,'depositWager','2.5');set(w,'depositBadge','hide','change');set(w,'orderMinutes','0');w.document.getElementById('saveFinance').click();const c=JSON.parse(w.localStorage.getItem('ngss3.deposit-payment-settings'));assert.equal(c.depositWager,'2.5');assert.equal(c.depositBadge,'hide');assert.equal(w.localStorage.getItem(w.RewardHub.KEY),null);d.window.close();});
check('permanent first-deposit player preview shows no invalid date',()=>{const initial=page('player.html'),c=initial.window.Reward.clone(initial.window.Reward.defaults),key=initial.window.Reward.KEY;c.basic={periodMode:'always',startAt:'2020-01-01',endAt:'2020-01-02'};initial.window.close();const d=page('player.html','',{[key]:c}),w=d.window;assert.match(w.document.getElementById('activityPeriod').textContent,/始终开启/);assert.doesNotMatch(w.document.body.textContent,/Invalid Date/);set(w,'futureDays','500');assert.doesNotMatch(w.document.getElementById('forecastResult').textContent,/不在活动期间/);d.window.close();});
check('removed targeting and marketing have no hidden effect after editing old settings',()=>{const original=page('index.html'),c=original.window.Reward.clone(original.window.Reward.defaults),key=original.window.Reward.KEY;c.basic={...original.window.DepositCatalogue.basic(),memberMode:'specified',memberLevels:['VIP9'],validFirst:999,marketing:true};original.window.close();const d=page('index.html','?edit=registration-first-deposit',{[key]:c}),w=d.window;for(const id of ['memberLevels','validFirst','validDeposit','validTurnover','validCount','marketing'])assert.equal(w.document.getElementById(id),null);assert.doesNotMatch(w.document.body.textContent,/参与会员层级|有效会员标准|营销活动|累计充值赠送上限/);assert.match(w.document.getElementById('basic').textContent,/单用户赠送上限/);w.document.getElementById('saveActivity').click();const saved=JSON.parse(w.localStorage.getItem(key));assert.equal(saved.basic.memberMode,undefined);assert.equal(saved.basic.validFirst,undefined);assert.equal(saved.basic.marketing,undefined);assert.equal(saved.ageEnabled,c.ageEnabled);d.window.close();});
check('all participation states have translated copy and cannot offer duplicate claims',()=>{for(const key of ['login','notstarted','ended','paused','blocked','unmet','used','limit','pending','unknown','rewardpending','rewardfailed','credited']){const d=page('player.html','?scenario='+key),w=d.window;assert.equal(w.document.getElementById('resultPanel').dataset.state,key);assert.ok(w.document.getElementById('resultTitle').textContent);if(key!=='unmet'){assert.equal(w.document.getElementById('primary').hidden,true);assert.equal(w.document.getElementById('stage').hidden,true);assert.equal(w.document.getElementById('futurePanel').hidden,true);}set(w,'locale','en','change');assert.doesNotMatch(w.document.getElementById('resultPanel').textContent,/[\u3400-\u9fff]/);d.window.close();}});
check('credited reward status survives activity expiration and never recalculates a paid amount',()=>{const initial=page('player.html'),w=initial.window,c=w.Reward.clone(w.Reward.defaults),key=w.Reward.KEY;c.basic={startAt:'2020-01-01',endAt:'2020-01-02'};initial.window.close();const d=page('deposit.html','?scenario=credited',{[key]:c}),dw=d.window;assert.equal(dw.document.getElementById('resultPanel').dataset.state,'credited');assert.equal(dw.document.getElementById('primary').hidden,true);assert.doesNotMatch(dw.document.getElementById('total').textContent,/0.00|预计/);dw.document.getElementById('stateAction').click();assert.equal(dw.document.getElementById('stateDetail').hidden,false);d.window.close();});
check('guide links to every participation state without adding player debug controls',()=>{const d=page('guide.html');assert.equal(d.window.document.querySelectorAll('#participation-states article').length,14);assert.ok(d.window.document.querySelector('a[href="player.html?scenario=blocked"]'));assert.ok(d.window.document.querySelector('a[href="player.html?scenario=credited"]'));d.window.close();});
console.log(n+' DOM checks passed; this does not verify browser layout or live payment services.');
