(() => {
  const $=s=>document.querySelector(s),read=path=>Number($('[data-path="'+path+'"]').value),esc=LJConfig.esc;
  const bar=$('.topbar'),nav=$('.section-nav'),header=document.createElement('div');header.className='editor-header';bar.before(header);header.append(bar,nav);
  const tools=document.createElement('details');tools.className='tool-menu';tools.innerHTML='<summary>更多工具 ▾</summary><div class="tool-menu-body"></div>';$('.actions').prepend(tools);
  ['themeBtn','restoreBtn','exportBtn','resetBtn'].forEach(id=>tools.lastElementChild.append($('#'+id)));const guide=$('.actions a[href="guide.html"]');tools.lastElementChild.append(guide);$('#saveBtn').classList.add('primary');$('#resetBtn').classList.add('danger-action');
  $('.sidebar').prepend($('.setting-checks'));$('.setting-checks').classList.add('check-card');
  const resize=()=>document.documentElement.style.setProperty('--editor-height',header.getBoundingClientRect().height+'px');if(window.ResizeObserver)new ResizeObserver(resize).observe(header);resize();
  function change(path,value){const input=$('[data-path="'+path+'"]');input.value=value;input.dispatchEvent(new Event('input',{bubbles:true}));}
  function allocation(node,labels,kind,onChange){
    if(node.updateAllocation)return;
    node.classList.add('allocation',kind);node.innerHTML='<div class="allocation-track">'+labels.map((label,i)=>`<span class="allocation-segment segment-${i}"></span>`).join('')+`<button type="button" class="allocation-handle" role="slider" aria-label="${labels[0]}与${labels[1]}分界" data-boundary="0"></button><button type="button" class="allocation-handle" role="slider" aria-label="${labels[1]}与${labels[2]}分界" data-boundary="1"></button></div><div class="allocation-legend"></div>`;
    const track=node.querySelector('.allocation-track'),handles=[...node.querySelectorAll('.allocation-handle')];let bounds=[0,100];const minimum=kind==='item-colors'?1:0;
    function update(index,value){const next=[...bounds];next[index]=Math.max(index?bounds[0]+minimum:minimum,Math.min(index?100-minimum:bounds[1]-minimum,Math.round(value)));onChange(next);}
    handles.forEach((handle,i)=>{handle.onpointerdown=e=>{e.preventDefault();handle.focus();handle.setPointerCapture?.(e.pointerId);const move=event=>{const r=track.getBoundingClientRect();if(r.width)update(i,(event.clientX-r.left)/r.width*100);};const stop=()=>{handle.removeEventListener('pointermove',move);handle.removeEventListener('pointerup',stop);handle.removeEventListener('pointercancel',stop);};handle.addEventListener('pointermove',move);handle.addEventListener('pointerup',stop);handle.addEventListener('pointercancel',stop);};handle.onkeydown=e=>{let value=bounds[i];if(['ArrowLeft','ArrowDown'].includes(e.key))value-=e.shiftKey?10:1;else if(['ArrowRight','ArrowUp'].includes(e.key))value+=e.shiftKey?10:1;else if(e.key==='Home')value=i?bounds[0]:0;else if(e.key==='End')value=i?100:bounds[1];else return;e.preventDefault();update(i,value);};});
    node.updateAllocation=values=>{bounds=[values[0],Math.round((values[0]+values[1])*100)/100];node.querySelectorAll('.allocation-segment').forEach((el,i)=>{el.style.width=values[i]+'%';el.title=labels[i]+' '+values[i]+'%';});handles.forEach((h,i)=>{h.style.left=bounds[i]+'%';h.setAttribute('aria-valuemin',i?bounds[0]+minimum:minimum);h.setAttribute('aria-valuemax',i?100-minimum:bounds[1]-minimum);h.setAttribute('aria-valuenow',bounds[i]);h.setAttribute('aria-valuetext',labels.map((label,j)=>label+' '+values[j]+'%').join('，'));});node.querySelector('.allocation-legend').innerHTML=labels.map((label,i)=>`<span><i class="segment-${i}"></i>${label} <b>${values[i]}%</b></span>`).join('');};
  }
  function draw(event){const current=event.detail;

    const name=$('#nameMode');if(!$('#nameSegments')){name.classList.add('control-hidden');const group=document.createElement('div');group.id='nameSegments';group.className='segmented';group.innerHTML='<button type="button" data-name="system">系统自带</button><button type="button" data-name="custom">自定义</button>';name.closest('.field').querySelector('label').after(group);group.onclick=e=>{if(e.target.dataset.name)change('basic.nameMode',e.target.dataset.name);};}
    document.querySelectorAll('[data-name]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.name===name.value)));
    if(!$('#milestones')){const m=document.createElement('div');m.id='milestones';m.className='milestones';$('.unlock-hero').append(m);}
    const T=read('targetSpins'),F=read('firstSpinPct');$('#milestones').innerHTML=`<span>首转范围 <b>${Number.isFinite(F)?(F-5)+'%–'+(F+5):'—'}%</b></span><i>→</i><span>中间 <b>${Number.isFinite(T)?T-2:'—'} 次</b></span><i>→</i><span>第 ${Number.isFinite(T)?T:'—'} 转 <b>100% 解锁</b></span>`;
    if(!$('#phaseSlider')){const el=document.createElement('div');el.id='phaseSlider';el.className='phase-slider';el.innerHTML='<div class="subhead"><b>次数分配</b><span class="muted">拖动分界点</span></div><div id="phaseAllocation"></div><div class="share-editors"></div>';$('.phase-grid').before(el);document.querySelectorAll('.phase').forEach((phase,i)=>{const group=document.createElement('div');group.className='share-editor';group.innerHTML='<h3>'+['快砍','中段','细砍'][i]+'</h3>';group.append(phase.querySelector('.phase-inline'));el.querySelector('.share-editors').append(group);});}
    const shares=['fast','mid','fine'].map(k=>read('phaseShares.'+k));allocation($('#phaseAllocation'),['快砍','中段','细砍'],'phase-colors',bounds=>document.dispatchEvent(new CustomEvent('lj-shares',{detail:bounds})));$('#phaseAllocation').updateAllocation(shares);
    document.querySelectorAll('.item-slider').forEach(node=>{const phase=node.dataset.phase;allocation(node,['金币','宝石','星钻'],'item-colors',bounds=>document.dispatchEvent(new CustomEvent('lj-weights',{detail:{phase,bounds}})));node.updateAllocation(['coin','gem','star'].map(k=>current.prize[phase].weights[k]));});
    const all=['sideFree','sideTask','sideAssist'].reduce((n,id)=>n+Number($('#'+id).textContent.replace(/[^0-9.]/g,'')),0);if(!$('#sourceGap')){const el=document.createElement('div');el.id='sourceGap';el.className='source-gap';$('#tickets .panel-body').prepend(el);}$('#sourceGap').classList.toggle('error',all<T);$('#sourceGap').textContent=`可得 ${all} 次 / 解锁 ${T} 次`+(all<T?` · 尚缺 ${T-all} 次，请增加来源次数。`:' · 次数充足');
    document.querySelectorAll('.source').forEach(source=>{const on=source.querySelector('.toggle input').checked;source.querySelector('.source-body').hidden=!on;source.classList.toggle('enabled',on);});
    document.querySelectorAll('.task-row>span:empty').forEach(el=>{el.textContent='累计达标';el.className='task-type';});
    const join=$('[data-path="budget.joinMode"]');if(join.closest('details')){const details=join.closest('details');details.before(details.querySelector('.form-grid'));details.remove();}
    if(!$('#joinHint')){const hint=document.createElement('p');hint.id='joinHint';hint.className='inline-hint';join.closest('.field').append(hint);}$('#joinHint').textContent=join.value==='auto'?'打开活动页即占用名额和奖金预留；须设置参加人数上限。':'点击参加后才占用名额和奖金预留。';
    document.querySelectorAll('input[type=number]').forEach(input=>{const invalid=!input.disabled&&!input.checkValidity();input.setAttribute('aria-invalid',String(invalid));const field=input.closest('.field');if(!field)return;let hint=field.querySelector('.field-error');if(!hint){hint=document.createElement('small');hint.className='field-error';hint.id=input.id?input.id+'-error':'';field.append(hint);}hint.hidden=!invalid;if(invalid){hint.textContent=input.value===''?'请输入数值':input.validity.rangeUnderflow?'不可低于 '+input.min:input.validity.rangeOverflow?'不可高于 '+input.max:'请按 '+input.step+' 的单位填写';if(hint.id)input.setAttribute('aria-describedby',hint.id);}else if(input.getAttribute('aria-describedby')===hint.id)input.removeAttribute('aria-describedby');});
    const curve=$('#curve');if(curve&&Number.isInteger(T)&&T>=4&&T<=30&&Number.isFinite(F)){const c=LJConfig.defaults();c.targetSpins=T;c.firstSpinPct=F;c.phaseShares=Object.fromEntries(['fast','mid','fine'].map((k,i)=>[k,shares[i]]));const rows=LuckyJourneyEngine.progressPreview(c),alloc=LuckyJourneyEngine.allocatePhaseSpins(T,c.phaseShares);[1,1+alloc.fast,1+alloc.fast+alloc.mid,T].forEach((k,i)=>{const r=rows[k],circle=document.createElementNS('http://www.w3.org/2000/svg','circle');circle.setAttribute('cx',34+k/T*650);circle.setAttribute('cy',116-r.progress*.94);circle.setAttribute('r',4);circle.setAttribute('fill',['#409eff','#e5b55b','#af91dd','#63bbaa'][i]);circle.innerHTML='<title>'+esc(`第 ${k} 转 · ${r.progress.toFixed(4)}%` )+'</title>';curve.append(circle);});}
  }
  document.addEventListener('lj-render',draw);document.dispatchEvent(new Event('lj-refresh'));
})();
