/* Embed adapter: consume the same resolved configuration as the NG player. */
(()=>{let c;const aliases={Home:'首页',Activity:'活动',Wallet:'钱包',Agent:'推广',Account:'账户',Deposit:'充值',Withdraw:'提款',Login:'登入注册','Join now':'登入注册','VIP benefits':'VIP','Customer support':'客服'};
function apply(){if(!c)return;const out=c.auth==='loggedOut',balance=document.querySelector('.balance');balance.querySelector('strong').textContent=out?'Log in':'86,617.36';balance.querySelector('small').hidden=out;balance.querySelector('.coin').hidden=out;
const v=c.values||{},home=c.current?.gameLayout?.home||{};document.querySelector('.money-actions').hidden=home.quick===false;document.querySelector('.activity').hidden=home.promotions===false;document.querySelector('.site-footer').hidden=v.footerStyle===null||v.footerStyle==='关闭';document.querySelector('.support').hidden=v.shortcuts===null||v.shortcuts==='关闭';
document.querySelectorAll('.embed-entry').forEach(n=>n.remove());
if(c.install){const b=document.createElement('button');b.className='embed-entry';b.textContent='⇩ App';b.onclick=()=>{const dialog=document.querySelector('dialog');dialog.querySelector('h2').textContent='Download App';dialog.querySelector('.dialog-copy').textContent='App download entry preview.';dialog.showModal()};document.querySelector('.site').append(b);}
const alt=v.alternateSpec;if(alt?.placement&&!v.alternateDisabled&&alt.target){const b=document.createElement('button');b.className='embed-entry alternate';b.textContent=alt.target;b.onclick=()=>parent.postMessage({type:'ngss3-preview-navigation',page:alt.target},location.protocol==='file:'?'*':location.origin);document.querySelector('.site').append(b);}
const nav=(c.nav||['首页','活动','钱包','推广','账户']).map(n=>n==='APP下载'&&c.appReplacement&&c.current?.bottomNav?.appReplacementEnabled?.[c.auth]?(c.current.bottomNav.appReplacement?.[c.auth]||n):n);document.querySelectorAll('[data-nav]').forEach((b,i)=>{b.dataset.resolvedNav=nav[i]||'';b.querySelector('b').textContent=({'首页':'Home','活动':'Activity','钱包':'Wallet','推广':'Agent','账户':'Account','VIP':'VIP','APP下载':'App'})[nav[i]]||nav[i];b.setAttribute('aria-current',nav[i]==='首页'?'page':'false')});}
window.addEventListener('message',e=>{if(e.source!==parent||parent===window||(location.protocol!=='file:'&&e.origin!==location.origin)||e.data?.type!=='ngss3-preview-config'||e.data.config?.theme!=='PH')return;c=e.data.config;apply()});
document.addEventListener('click',e=>{if(!c)return;const b=e.target.closest('[data-nav],[data-dialog]');if(!b)return;const n=b.dataset.resolvedNav||aliases[b.dataset.nav||b.dataset.dialog];if(!n)return;e.preventDefault();e.stopImmediatePropagation();parent.postMessage({type:'ngss3-preview-navigation',page:c.auth==='loggedOut'&&['钱包','充值','提款','账户'].includes(n)?'登入注册':n},location.protocol==='file:'?'*':location.origin);},true);
if(parent!==window)parent.postMessage({type:'ngss3-preview-ready'},location.protocol==='file:'?'*':location.origin);
})();
