(()=>{
'use strict';
const shapes={menu:'M3 6h18M3 12h12M3 18h18',diamond:'m7 3-5 7 10 12 10-12-5-7Zm-5 7h20M7 3l5 19 5-19M7 3l5 7 5-7',plus:'M12 4v16M4 12h16',home:'m3 10 9-7 9 7M5 9v12h5v-7h4v7h5V9',gift:'M3 9h18v4H3zM5 13v9h14v-9M12 9v13M12 9C3 9 5 1 9 4l3 5Zm0 0c9 0 7-8 3-5l-3 5Z',wallet:'m3 6 15-4v17l-15 3Zm3 2v10M18 7h3v14H8M13 12h1',agent:'M8 10a4 4 0 1 0 0-8 4 4 0 0 0 0 8Zm10 0a3 3 0 1 0 0-6M2 14c5-3 11-1 13 3-1 4-4 5-7 5-4-1-6-4-6-8Zm14 0c4-1 6 1 6 4l-4 3',account:'M12 22a10 10 0 1 0 0-20 10 10 0 0 0 0 20Zm0-11a4 4 0 1 0 0-8 4 4 0 0 0 0 8ZM5 19c1-7 13-7 14 0',game:'M7 5h10c5 0 8 15 3 15l-5-4H9l-5 4C-1 20 2 5 7 5Zm-2 5h6M8 7v6M16 10h.1M19 13h.1',search:'M10 17a7 7 0 1 0 0-14 7 7 0 0 0 0 14Zm5-2 6 6',filter:'M3 6h18M3 12h18M3 18h18M8 4v4M16 10v4M10 16v4',headset:'M4 13v-3a8 8 0 0 1 16 0v3M4 12H2v7h5v-7H4Zm16 0h2v7h-5v-7h3ZM20 19v3h-7',candy:'m7 6 10 12M4 4l4 1-3 4-2-4Zm16 16-4-1 3-4 2 4ZM9 6C1 11 13 24 18 16 23 9 15 1 9 6Z',trophy:'M7 3h10v9c0 6-10 6-10 0V3ZM7 6H3v3c0 4 4 4 4 4M17 6h4v3c0 4-4 4-4 4M12 17v4M7 22h10',share:'m8 11 8-5M8 14l8 5M5 16a4 4 0 1 0 0-8 4 4 0 0 0 0 8ZM19 8a3 3 0 1 0 0-6 3 3 0 0 0 0 6Zm0 14a3 3 0 1 0 0-6 3 3 0 0 0 0 6Z',spark:'m8 2 2 5 5 2-5 2-2 5-2-5-5-2 5-2Zm10 9 1 4 4 1-4 1-1 4-1-4-4-1 4-1',flame:'M13 2c0 7 8 7 7 14-1 8-17 8-16-1 0-4 4-5 4-9 2 2 3 5 2 7 3-1 4-7 3-11',star:'m12 2 3 6 7 1-5 5 1 8-6-4-6 4 1-8-5-5 7-1Z',slots:'M4 5h16v15H4ZM7 10l3 0-2 6M12 10h3l-2 6M17 2v3',close:'m5 5 14 14M19 5 5 19'};
const icon=n=>`<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="${shapes[n]||shapes.spark}"/></svg>`;
const img=(n,cl='',alt='')=>`<img class="${cl}" src="assets/${n}.webp" alt="${alt}" draggable="false">`;
const heading=(symbol,title,extra='')=>`<div class="section-heading"><span class="heading-icon">${icon(symbol)}</span><h2>${title}</h2>${extra}</div>`;
const games=[['pinata-wins','PINATA WINS','Slots'],['aztec-idols','Aztec Idols','Slots'],['sugar-bang-bang','Sugar Bang Bang','Slots'],['fortune-gems','Fortune Gems','Slots'],['fortune-gems-2','Fortune Gems 2','Slots'],['fortune-gems-3','Fortune Gems 3','Slots'],['golden-empire','Golden Empire','Slots'],['super-ace','Super Ace','Slots'],['wild-ace','Wild Ace','Slots'],['mahjong-ways-2','Mahjong Ways 2','Slots'],['wild-ape','Wild Ape','Slots'],['wild-bandito','Wild Bandito','Slots'],['wild-bounty','Wild Bounty Showdown','Slots'],['redgreen-light','RedGreen Light','Lottery'],['5min-wingo','5Min Wingo','Lottery'],['10min-wingo','10Min Wingo','Lottery']];
const socials=[['Viber','viber','☎'],['Facebook','facebook','f'],['What App','whatsapp','◉'],['Instagram','instagram','◎'],['Telegram','telegram','➤'],['Youtube','youtube','▶'],['X','x','𝕏']];
document.querySelector('#app').innerHTML=`
<header class="site-header"><button class="icon-button menu-toggle" aria-label="Open menu">${icon('menu')}</button><div class="header-center">${img('logo','brand','JLJL4')}<button class="balance" data-dialog="Wallet"><span class="coin">$</span><span><strong>86,617.36</strong><small>368.12</small></span><span class="balance-plus">${icon('plus')}</span></button></div><button class="icon-button vip-button" aria-label="VIP benefits" data-dialog="VIP benefits">${icon('diamond')}</button></header>
<main>
<section class="hero" aria-label="Promotional offers"><div class="hero-backdrop"></div>${img('hero-character','hero-character')}<div class="hero-copy"><div class="offer-ribbon">Deposit <mark>200%</mark> Bonus Now !</div><h1><span>WELCOME</span><strong>BIG WINS</strong><span>NOW !!!</span></h1><p>More Bonuses More Rewards</p><button class="join" data-dialog="Join now">Join Now</button></div><div class="hero-dots" role="group" aria-label="Choose promotion">${[0,1,2,3].map(i=>`<button data-slide="${i}" aria-label="Promotion ${i+1}" aria-pressed="${i===0}"></button>`).join('')}</div></section>
<div class="money-actions"><button data-dialog="Deposit">${img('deposit')}<span>Deposit</span></button><button data-dialog="Withdraw">${img('withdraw')}<span>Withdraw</span></button></div>
<section id="activity" class="activity">${heading('candy','Activity')}<div class="bonus-task">${img('gift','bonus-gift')}<div class="bonus-title"><h3>Bonus Task</h3><span><b>1000</b> people completed the task today.</span></div><div class="bonus-body"><button class="login-coin" data-dialog="Login">LOGIN</button><div class="ticket-scroll" aria-label="Bonus tasks">${[90,80,60].map((n,i)=>`<button class="ticket" data-dialog="${i===0?'New user benefit tasks':'Daily benefit tasks'}"><span class="ticket-value"><strong><small>$</small>${n}</strong><b>Highest Reward</b></span><span class="ticket-copy"><strong>${i===0?'New User':'Daily'} Benefit Tasks</strong><small>Login to get Bonus</small></span></button>`).join('')}</div></div></div></section>
<section id="games" class="games-section">${heading('game','Game',img('pirate','pirate'))}<div class="game-panel"><div class="game-tabs" role="group" aria-label="Game categories">${[['Popular','flame'],['Feature','star'],['Slots','slots'],['Lottery','diamond']].map(([n,i],k)=>`<button data-category="${n}" aria-pressed="${k===0}">${icon(i)}${n}</button>`).join('')}</div><div class="game-search">${icon('search')}<input type="search" placeholder="Game name" aria-label="Search games"><button class="icon-button filter-button" aria-label="Filter game type" aria-expanded="false">${icon('filter')}</button></div><div class="provider-filters" hidden><button data-provider="all" aria-pressed="true">All types</button><button data-provider="slots" aria-pressed="false">Slots</button><button data-provider="lottery" aria-pressed="false">Lottery</button></div><div class="game-grid">${games.map(([n,title,category],i)=>`<button class="game-card" data-game="${title}" data-type="${category}" data-feature="${i%3===0}" aria-label="Play ${title}">${img(n,'',title)}</button>`).join('')}</div><p class="empty-state" hidden>No games found. Try another name.</p></div></section>
<section id="wins" class="wins">${heading('trophy','Recent Big Wins',img('trophy-glow','trophy-glow'))}<div class="winners-picture">${img('winners-art','','Recent Big Win podium: three players, each with a win of 3820')}</div></section>
<section id="share" class="share">${heading('share','Share')}<div class="social-grid">${socials.map(([label,n,glyph])=>`<button class="social ${n}" data-share="${label}"><span class="social-icon">${glyph}</span><strong>${label}</strong><span class="share-pill">Share</span></button>`).join('')}</div></section>
<section class="providers">${heading('spark','Game Provider')}<div class="provider-logos">${[['provider-tada','TaDa Gaming'],['provider-jdb','JDB'],['provider-dream','Dream Gaming']].map(([n,alt])=>`<button data-dialog="${alt}">${img(n,'',alt)}</button>`).join('')}</div></section>
<footer class="site-footer">${img('logo','','JLJL4')}<p>Welcome! Here's a brief introduction to the site.<br>Welcome! Here's a brief introduction to the site.</p></footer>
</main>
<button class="support" data-dialog="Customer support" aria-label="Customer support">${icon('headset')}</button>
<nav class="bottom-nav" aria-label="Main navigation">${img('nav-crown','nav-crown')}${[['Home','home'],['Activity','gift'],['Wallet','wallet'],['Agent','agent'],['Account','account']].map(([n,i],k)=>`<button data-nav="${n}" ${k===0?'aria-current="page"':''} class="${n==='Wallet'?'wallet-tab':''}"><span>${icon(i)}</span><b>${n}</b></button>`).join('')}</nav>
<dialog class="demo-dialog"><button class="dialog-close icon-button" aria-label="Close dialog">${icon('close')}</button><span class="dialog-emblem">${icon('diamond')}</span><h2></h2><p class="dialog-copy"></p><button class="dialog-done">Got it</button></dialog>
<div class="menu-backdrop" hidden></div><aside class="side-menu" aria-label="Site menu" hidden><div>${img('logo','','JLJL4')}<button class="menu-close icon-button" aria-label="Close menu">${icon('close')}</button></div>${['Home','Activity','Game','Recent Big Wins','Share'].map(n=>`<button data-menu="${n}">${n}<span>›</span></button>`).join('')}</aside><div class="toast" role="status" aria-live="polite"></div>`;
const dialog=document.querySelector('dialog');let lastFocus;
function openDialog(title,copy='This is a standalone design preview. No account or payment action is performed.'){lastFocus=document.activeElement;dialog.querySelector('h2').textContent=title;dialog.querySelector('.dialog-copy').textContent=copy;dialog.showModal();}
function closeDialog(){dialog.close();lastFocus?.focus({preventScroll:true});}
document.querySelectorAll('[data-dialog]').forEach(b=>b.onclick=()=>openDialog(b.dataset.dialog));document.querySelectorAll('.dialog-close,.dialog-done').forEach(b=>b.onclick=closeDialog);dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)closeDialog();}});
document.querySelectorAll('[data-game]').forEach(b=>b.onclick=()=>openDialog(b.dataset.game,'Game launch preview. Choose another game to compare artwork and layout.'));
const destinations={Home:0,Activity:'#activity',Game:'#games','Recent Big Wins':'#wins',Share:'#share'};function jump(name){if(name==='Home')window.scrollTo({top:0,behavior:'smooth'});else document.querySelector(destinations[name])?.scrollIntoView({behavior:'smooth',block:'start'});}
document.querySelectorAll('[data-nav]').forEach(b=>b.onclick=()=>{if(['Home','Activity'].includes(b.dataset.nav)){document.querySelectorAll('[data-nav]').forEach(x=>x.removeAttribute('aria-current'));b.setAttribute('aria-current','page');jump(b.dataset.nav);}else openDialog(b.dataset.nav);});
let lastMenuFocus;function menu(open){if(open)lastMenuFocus=document.activeElement;document.querySelector('.side-menu').hidden=!open;document.querySelector('.menu-backdrop').hidden=!open;document.querySelector('.menu-toggle').setAttribute('aria-expanded',String(open));if(open)document.querySelector('.menu-close').focus();else lastMenuFocus?.focus({preventScroll:true});}
document.querySelector('.menu-toggle').onclick=()=>menu(true);document.querySelector('.menu-close').onclick=()=>menu(false);document.querySelector('.menu-backdrop').onclick=()=>menu(false);document.querySelectorAll('[data-menu]').forEach(b=>b.onclick=()=>{menu(false);jump(b.dataset.menu);});document.addEventListener('keydown',e=>{const panel=document.querySelector('.side-menu');if(panel.hidden)return;if(e.key==='Escape'){menu(false);return;}if(e.key==='Tab'){const items=[...panel.querySelectorAll('button')],first=items[0],last=items.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}});
let activeCategory='Popular',activeProvider='all';function filter(){let count=0;const term=document.querySelector('.game-search input').value.trim().toLowerCase();document.querySelectorAll('[data-game]').forEach(b=>{const category=activeCategory==='Popular'||activeCategory==='Feature'&&b.dataset.feature==='true'||activeCategory===b.dataset.type;const provider=activeProvider==='all'||activeProvider===b.dataset.type.toLowerCase();b.hidden=!(category&&provider&&b.dataset.game.toLowerCase().includes(term));if(!b.hidden)count++;});document.querySelector('.empty-state').hidden=count>0;sendHeight();}
document.querySelector('.game-search input').oninput=filter;document.querySelectorAll('[data-category]').forEach(b=>b.onclick=()=>{activeCategory=b.dataset.category;document.querySelectorAll('[data-category]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));filter();});document.querySelector('.filter-button').onclick=()=>{const box=document.querySelector('.provider-filters');box.hidden=!box.hidden;document.querySelector('.filter-button').setAttribute('aria-expanded',String(!box.hidden));sendHeight();};document.querySelectorAll('[data-provider]').forEach(b=>b.onclick=()=>{activeProvider=b.dataset.provider;document.querySelectorAll('[data-provider]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));filter();});
const slides=[['WELCOME','BIG WINS','NOW !!!'],['PLAY MORE','WIN MORE','TODAY !'],['YOUR NEXT','BIG WIN','IS HERE !'],['GET READY','LET’S PLAY','JOIN NOW !']];document.querySelectorAll('[data-slide]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-slide]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));const [a,c,d]=slides[Number(b.dataset.slide)];document.querySelector('.hero h1').innerHTML=`<span>${a}</span><strong>${c}</strong><span>${d}</span>`;});
document.querySelectorAll('[data-share]').forEach(b=>b.onclick=()=>openDialog('Share on '+b.dataset.share,'Share button preview. This demo does not post or send messages.'));
function sendHeight(){if(window.parent!==window)window.parent.postMessage({type:'crimson-height',height:document.querySelector('.site').scrollHeight},'*');}window.addEventListener('load',sendHeight);new ResizeObserver(sendHeight).observe(document.querySelector('.site'));
})();
